package com.rave.visiit.entity;
// default package
// Generated 24 Dec, 2014 7:54:49 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.rave.visiit.util.Constants;

/**
 * AppLogin generated by hbm2java
 */
@Entity
@Table(name = "app_login", catalog = Constants.DB_CATELOG)
public class AppLogin implements java.io.Serializable {

	private Integer loginSeqId;
	private User users;
	private Date loginTime;

	public AppLogin() {
	}

	public AppLogin(User users, Date loginTime) {
		this.users = users;
		this.loginTime = loginTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "login_seq_id", unique = true, nullable = false)
	public Integer getLoginSeqId() {
		return this.loginSeqId;
	}

	public void setLoginSeqId(Integer loginSeqId) {
		this.loginSeqId = loginSeqId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "login_user_id", nullable = false)
	public User getUsers() {
		return this.users;
	}

	public void setUsers(User users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "login_time", nullable = false, length = 0)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

}
