package com.rave.visiit.entity;
// default package
// Generated 31 Jan, 2015 7:33:34 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.rave.visiit.util.Constants;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country", catalog = Constants.DB_CATELOG)
public class Country implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer countryId;
	private String countryCode;
	private String countryName;
	private String countryDescription;
	private Boolean countryIsactive = Boolean.TRUE;
	private Date countryUpdatedDate;
	private Boolean isDeleted = Boolean.FALSE;
	@Transient
	private String activeModel;
	private String modifiedBy;
	private Date createdOn;
	private String createdBy;
	//private Set<State> states = new HashSet<State>(0);

	public Country() {
	}

	public Country(String countryCode, String countryName,
			Boolean countryIsactive, Date countryUpdatedDate,Boolean isDeleted) {
		this.countryCode = countryCode;
		this.countryName = countryName;
		this.countryIsactive = countryIsactive;
		this.countryUpdatedDate = countryUpdatedDate;
		this.isDeleted = isDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "country_id", unique = true, nullable = false)
	public Integer getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	@Column(name = "country_code", nullable = false, length = 30)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "country_name", nullable = false, length = 50)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "country_description", length = 150)
	public String getCountryDescription() {
		return this.countryDescription;
	}

	public void setCountryDescription(String countryDescription) {
		this.countryDescription = countryDescription;
	}

	@Column(name = "country_is_active", nullable = false, length = 6)
	public Boolean getCountryIsactive() {
		return this.countryIsactive;
	}

	public void setCountryIsactive(Boolean countryIsactive) {
		this.countryIsactive = countryIsactive;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "country_updated_date", nullable = false, length = 0)
	public Date getCountryUpdatedDate() {
		return this.countryUpdatedDate;
	}

	public void setCountryUpdatedDate(Date countryUpdatedDate) {
		this.countryUpdatedDate = countryUpdatedDate;
	}
	
	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}
	
	

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE})
	public Set<State> getStates() {
		return this.states;
	}

	public void setStates(Set<State> states) {
		this.states = states;
	}*/
	@Transient
	public String getActiveModel() {
		if(countryIsactive != null && countryIsactive){
			this.activeModel = "Y";
		} else {
			this.activeModel = "N";
		}
		return activeModel;
	}

	public void setActiveModel(String activeModel) {
		this.activeModel = activeModel;
		
	}
	
	@Column(name = "modified_by")
	public String getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 0)
	public Date getCreatedOn() {
		return createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}
	
	@Column(name = "created_by")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	
}
