package com.rave.visiit.entity;
// default package
// Generated 24 Dec, 2014 7:54:49 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.rave.visiit.util.Constants;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = Constants.DB_CATELOG)
public class Department implements java.io.Serializable {

	private static final long serialVersionUID = 5738055031249418247L;

	private Integer deptId;
	private String deptCode;
	private String deptName;
	private String deptDescription;
	private Boolean deptIsActive = Boolean.TRUE;
	private Boolean isDeleted = Boolean.FALSE;
	private String deptCreatedBy;
	private Timestamp deptCreatedOn;
	private String deptModifiedBy;
	private Timestamp deptModifiedOn;

	public Department() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "dept_id", unique = true, nullable = false)
	public Integer getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	@Column(name = "dept_code", nullable = false, length = 30)
	public String getDeptCode() {
		return this.deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	@Column(name = "dept_name", nullable = false, length = 50)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "dept_description", length = 100)
	public String getDeptDescription() {
		return this.deptDescription;
	}

	public void setDeptDescription(String deptDescription) {
		this.deptDescription = deptDescription;
	}

	@Column(name = "dept_is_active")
	public Boolean getDeptIsActive() {
		return deptIsActive;
	}

	public void setDeptIsActive(Boolean deptIsActive) {
		this.deptIsActive = deptIsActive;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "dept_created_by")
	public String getDeptCreatedBy() {
		return deptCreatedBy;
	}

	public void setDeptCreatedBy(String deptCreatedBy) {
		this.deptCreatedBy = deptCreatedBy;
	}

	@Column(name = "dept_created_on")
	public Timestamp getDeptCreatedOn() {
		return deptCreatedOn;
	}

	public void setDeptCreatedOn(Timestamp deptCreatedOn) {
		this.deptCreatedOn = deptCreatedOn;
	}

	@Column(name = "dept_modified_by")
	public String getDeptModifiedBy() {
		return deptModifiedBy;
	}

	public void setDeptModifiedBy(String deptModifiedBy) {
		this.deptModifiedBy = deptModifiedBy;
	}

	@Column(name = "dept_modified_on")
	public Timestamp getDeptModifiedOn() {
		return deptModifiedOn;
	}

	public void setDeptModifiedOn(Timestamp deptModifiedOn) {
		this.deptModifiedOn = deptModifiedOn;
	}

}
