package com.rave.visiit.entity;
// default package
// Generated 24 Dec, 2014 7:54:49 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.rave.visiit.util.Constants;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name = "departments", catalog = Constants.DB_CATELOG)
public class Departments implements java.io.Serializable {

	private Integer deptId;
	private String deptCode;
	private String deptName;
	private String deptDescription;
	private String deptIsactive;
	private Date deptUpdatedDate;

	public Departments() {
	}

	public Departments(String deptCode, String deptName,
			String deptDescription, String deptIsactive, Date deptUpdatedDate) {
		this.deptCode = deptCode;
		this.deptName = deptName;
		this.deptDescription = deptDescription;
		this.deptIsactive = deptIsactive;
		this.deptUpdatedDate = deptUpdatedDate;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "dept_id", unique = true, nullable = false)
	public Integer getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	@Column(name = "dept_code", nullable = false, length = 30)
	public String getDeptCode() {
		return this.deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	@Column(name = "dept_name", nullable = false, length = 50)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "dept_description", nullable = false, length = 100)
	public String getDeptDescription() {
		return this.deptDescription;
	}

	public void setDeptDescription(String deptDescription) {
		this.deptDescription = deptDescription;
	}

	@Column(name = "dept_isactive", nullable = false, length = 1)
	public String getDeptIsactive() {
		return this.deptIsactive;
	}

	public void setDeptIsactive(String deptIsactive) {
		this.deptIsactive = deptIsactive;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dept_updated_date", nullable = false, length = 0)
	public Date getDeptUpdatedDate() {
		return this.deptUpdatedDate;
	}

	public void setDeptUpdatedDate(Date deptUpdatedDate) {
		this.deptUpdatedDate = deptUpdatedDate;
	}

	@Override
	public String toString() {
		return "Departments [deptId=" + deptId + ", deptCode=" + deptCode
				+ ", deptName=" + deptName + ", deptDescription="
				+ deptDescription + ", deptIsactive=" + deptIsactive
				+ ", deptUpdatedDate=" + deptUpdatedDate + "]";
	}

}
