package com.rave.visiit.entity;
// default package
// Generated 24 Dec, 2014 7:54:49 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.rave.visiit.util.Constants;

/**
 * Designation generated by hbm2java
 */
@Entity
@Table(name = "designation", catalog = Constants.DB_CATELOG)
public class Designation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4686368880667443784L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "dsg_id", unique = true, nullable = false)
	private Integer dsgId;
	
	@Column(name = "dsg_code", nullable = false, length = 30)
	private String dsgCode;
	
	@Column(name = "dsg_name", nullable = false, length = 50)
	private String dsgName;
	
	@Column(name = "dsg_level")
	private Integer dsgLevel;
	
	@Column(name = "dsg_description", length = 100)
	private String dsgDescription;
	
	@Column(name = "dsg_is_active")
	private boolean dsgIsActive = true;
	
	@Column(name = "is_deleted")
	private boolean isDeleted = false;
	
	@Column(name = "dsg_modified_on")
	private Timestamp dsgModifiedOn;

	@Column(name = "dsg_created_on", nullable = false, length = 0)
	private Timestamp dsgCreatedOn;
	
	@Column(name = "dsg_created_by", nullable = false, length = 30)
	private String dsgCreatedBy;
	
	@Column(name = "dsg_modified_by")
	private String dsgModifiedBy;
	
	public Integer getDsgId() {
		return dsgId;
	}

	public void setDsgId(Integer dsgId) {
		this.dsgId = dsgId;
	}

	public String getDsgCode() {
		return dsgCode;
	}

	public void setDsgCode(String dsgCode) {
		this.dsgCode = dsgCode;
	}

	public String getDsgName() {
		return dsgName;
	}

	public void setDsgName(String dsgName) {
		this.dsgName = dsgName;
	}

	public Integer getDsgLevel() {
		return dsgLevel;
	}

	public void setDsgLevel(Integer dsgLevel) {
		this.dsgLevel = dsgLevel;
	}

	public String getDsgDescription() {
		return dsgDescription;
	}

	public void setDsgDescription(String dsgDescription) {
		this.dsgDescription = dsgDescription;
	}

	public boolean isDsgIsActive() {
		return dsgIsActive;
	}

	public void setDsgIsActive(boolean dsgIsActive) {
		this.dsgIsActive = dsgIsActive;
	}

	public boolean isDeleted() {
		return isDeleted;
	}

	public void setDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Timestamp getDsgModifiedOn() {
		return dsgModifiedOn;
	}

	public void setDsgModifiedOn(Timestamp dsgModifiedOn) {
		this.dsgModifiedOn = dsgModifiedOn;
	}

	public Timestamp getDsgCreatedOn() {
		return dsgCreatedOn;
	}

	public void setDsgCreatedOn(Timestamp dsgCreatedOn) {
		this.dsgCreatedOn = dsgCreatedOn;
	}

	public String getDsgCreatedBy() {
		return dsgCreatedBy;
	}

	public void setDsgCreatedBy(String dsgCreatedBy) {
		this.dsgCreatedBy = dsgCreatedBy;
	}

	public String getDsgModifiedBy() {
		return dsgModifiedBy;
	}

	public void setDsgModifiedBy(String dsgModifiedBy) {
		this.dsgModifiedBy = dsgModifiedBy;
	}

}
