package com.rave.visiit.entity;
// default package
// Generated 24 Dec, 2014 7:54:49 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.rave.visiit.util.Constants;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name = "employees", catalog = Constants.DB_CATELOG)
public class Employees implements java.io.Serializable {

	private Integer empId;
	private Integer designation;
	private Integer departments;
	private String empCode;
	private String empFirstName;
	private String empLastName;
	private String empOfficeMail;
	private String empMail;
	private String empPhone;
	private String empExtentionNo;
	private Date empDoj;
	private String empEsiNo;
	private String empPanNo;
	private String empPassportNo;
	private String empPfNo;
	private Date empDate;
	private String empStatus;
	private Date empUpdatedDate;
	private String empUpdatedBy;

	public Employees() {
	}

	public Employees(Integer designation, Integer departments,
			String empCode, String empFirstName, String empLastName,
			String empOfficeMail, String empMail, String empPhone,
			String empExtentionNo, Date empDoj, String empEsiNo,
			String empPanNo, String empPassportNo, String empPfNo,
			Date empDate, String empStatus, Date empUpdatedDate) {
		this.designation = designation;
		this.departments = departments;
		this.empCode = empCode;
		this.empFirstName = empFirstName;
		this.empLastName = empLastName;
		this.empOfficeMail = empOfficeMail;
		this.empMail = empMail;
		this.empPhone = empPhone;
		this.empExtentionNo = empExtentionNo;
		this.empDoj = empDoj;
		this.empEsiNo = empEsiNo;
		this.empPanNo = empPanNo;
		this.empPassportNo = empPassportNo;
		this.empPfNo = empPfNo;
		this.empDate = empDate;
		this.empStatus = empStatus;
		this.empUpdatedDate = empUpdatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "emp_id", unique = true, nullable = false)
	public Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	@Column(name = "emp_dsg_id", nullable = false)
	public Integer getDesignation() {
		return this.designation;
	}

	public void setDesignation(Integer designation) {
		this.designation = designation;
	}

	@Column(name = "emp_dept_id", nullable = false)
	public Integer getDepartments() {
		return this.departments;
	}

	public void setDepartments(Integer departments) {
		this.departments = departments;
	}

	@Column(name = "emp_code", nullable = false, length = 30)
	public String getEmpCode() {
		return this.empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	@Column(name = "emp_first_name", nullable = false, length = 30)
	public String getEmpFirstName() {
		return this.empFirstName;
	}

	public void setEmpFirstName(String empFirstName) {
		this.empFirstName = empFirstName;
	}

	@Column(name = "emp_last_name", nullable = false, length = 30)
	public String getEmpLastName() {
		return this.empLastName;
	}

	public void setEmpLastName(String empLastName) {
		this.empLastName = empLastName;
	}

	@Column(name = "emp_office_mail", nullable = false, length = 50)
	public String getEmpOfficeMail() {
		return this.empOfficeMail;
	}

	public void setEmpOfficeMail(String empOfficeMail) {
		this.empOfficeMail = empOfficeMail;
	}

	@Column(name = "emp_mail", nullable = false, length = 50)
	public String getEmpMail() {
		return this.empMail;
	}

	public void setEmpMail(String empMail) {
		this.empMail = empMail;
	}

	@Column(name = "emp_phone", nullable = false, length = 15)
	public String getEmpPhone() {
		return this.empPhone;
	}

	public void setEmpPhone(String empPhone) {
		this.empPhone = empPhone;
	}

	@Column(name = "emp_extention_no", nullable = false, length = 10)
	public String getEmpExtentionNo() {
		return this.empExtentionNo;
	}

	public void setEmpExtentionNo(String empExtentionNo) {
		this.empExtentionNo = empExtentionNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "emp_doj", nullable = false, length = 0)
	public Date getEmpDoj() {
		return this.empDoj;
	}

	public void setEmpDoj(Date empDoj) {
		this.empDoj = empDoj;
	}

	@Column(name = "emp_esi_no", nullable = false, length = 20)
	public String getEmpEsiNo() {
		return this.empEsiNo;
	}

	public void setEmpEsiNo(String empEsiNo) {
		this.empEsiNo = empEsiNo;
	}

	@Column(name = "emp_pan_no", nullable = false, length = 20)
	public String getEmpPanNo() {
		return this.empPanNo;
	}

	public void setEmpPanNo(String empPanNo) {
		this.empPanNo = empPanNo;
	}

	@Column(name = "emp_passport_no", nullable = false, length = 20)
	public String getEmpPassportNo() {
		return this.empPassportNo;
	}

	public void setEmpPassportNo(String empPassportNo) {
		this.empPassportNo = empPassportNo;
	}

	@Column(name = "emp_pf_no", nullable = false, length = 20)
	public String getEmpPfNo() {
		return this.empPfNo;
	}

	public void setEmpPfNo(String empPfNo) {
		this.empPfNo = empPfNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "emp_date", nullable = false, length = 0)
	public Date getEmpDate() {
		return this.empDate;
	}

	public void setEmpDate(Date empDate) {
		this.empDate = empDate;
	}

	@Column(name = "emp_status", nullable = false, length = 1)
	public String getEmpStatus() {
		return this.empStatus;
	}

	public void setEmpStatus(String empStatus) {
		this.empStatus = empStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "emp_updated_date", nullable = false, length = 0)
	public Date getEmpUpdatedDate() {
		return this.empUpdatedDate;
	}

	public void setEmpUpdatedDate(Date empUpdatedDate) {
		this.empUpdatedDate = empUpdatedDate;
	}

	@Column(name = "emp_updated_by", length = 50)
	public String getEmpUpdatedBy() {
		return this.empUpdatedBy;
	}

	public void setEmpUpdatedBy(String empUpdatedBy) {
		this.empUpdatedBy = empUpdatedBy;
	}


}
