package com.rave.visiit.entity;
// default pack
// Generated 13 Feb, 2015 1:07:51 PM by Hibernate Tools 3.4.0.CR1


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.rave.visiit.util.Constants;

/**
 * Featuredpack generated by hbm2java
 */
@Entity
@Table(name="featured_package"
    ,catalog=Constants.DB_CATELOG
)
public class Featuredpackage  implements java.io.Serializable {
	
	 private Integer fpkId;
     private Integer pack;
     private Integer fpkOrder;
     private String fpkIsActive;
     private Date fpkModifiedOn;
     private String fpkModifiedBy;

    public Featuredpackage() {
    }

    public Featuredpackage(Integer pack, Integer fpkOrder, String fpkIsActive, Date fpkModifiedOn, String fpkModifiedBy) {
       this.pack = pack;
       this.fpkOrder = fpkOrder;
       this.fpkIsActive = fpkIsActive;
       this.fpkModifiedOn = fpkModifiedOn;
       this.fpkModifiedBy = fpkModifiedBy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="fpk_id", unique=true, nullable=false)
    public Integer getFpkId() {
        return this.fpkId;
    }
    
    public void setFpkId(Integer fpkId) {
        this.fpkId = fpkId;
    }

    @Column(name="fpk_pk_id", nullable=false)
    public Integer getPack() {
        return this.pack;
    }
    
    public void setPack(Integer pack) {
        this.pack = pack;
    }

    @Column(name="fpk_order")
    public Integer getFpkOrder() {
        return this.fpkOrder;
    }
    
    public void setFpkOrder(Integer fpkOrder) {
        this.fpkOrder = fpkOrder;
    }

    
    @Column(name="fpk_isActive", length=2)
    public String getFpkIsActive() {
        return this.fpkIsActive;
    }
    
    public void setFpkIsActive(String fpkIsActive) {
        this.fpkIsActive = fpkIsActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fpk_modified_on", length=0)
    public Date getFpkModifiedOn() {
        return this.fpkModifiedOn;
    }
    
    public void setFpkModifiedOn(Date fpkModifiedOn) {
        this.fpkModifiedOn = fpkModifiedOn;
    }

    
    @Column(name="fpk_modified_by", nullable=false, length=30)
    public String getFpkModifiedBy() {
        return this.fpkModifiedBy;
    }
    
    public void setFpkModifiedBy(String fpkModifiedBy) {
        this.fpkModifiedBy = fpkModifiedBy;
    }


}


