package com.rave.visiit.entity;
// default package
// Generated 30 Dec, 2014 2:39:28 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.rave.visiit.util.Constants;

/**
 * HotelContact generated by hbm2java
 */
@Entity
@Table(name = "hotel_contact", catalog = Constants.DB_CATELOG)
public class HotelContact implements java.io.Serializable {

	private Integer hcSeqId;
	private int hotelDetail;
	private String hcContactName1;
	private String hcPosition1;
	private String hcPhone1;
	private String hcEmail1;
	private String hcContactName2;
	private String hcPosition2;
	private String hcPhone2;
	private String hcEmail2;
	private String hcIsactive;
	private Date hcModifiedOn;
	private String hcModifiedBy;

	public HotelContact() {
	}

	public HotelContact(int hotelDetail, String hcContactName1,
			String hcPhone1, String hcEmail1, String hcContactName2,
			String hcPhone2, String hcEmail2, String hcIsactive,
			Date hcModifiedOn, String hcModifiedBy) {
		this.hotelDetail = hotelDetail;
		this.hcContactName1 = hcContactName1;
		this.hcPhone1 = hcPhone1;
		this.hcEmail1 = hcEmail1;
		this.hcContactName2 = hcContactName2;
		this.hcPhone2 = hcPhone2;
		this.hcEmail2 = hcEmail2;
		this.hcIsactive = hcIsactive;
		this.hcModifiedOn = hcModifiedOn;
		this.hcModifiedBy = hcModifiedBy;
	}

	public HotelContact(int hotelDetail, String hcContactName1,
			String hcPosition1, String hcPhone1, String hcEmail1,
			String hcContactName2, String hcPosition2, String hcPhone2,
			String hcEmail2, String hcIsactive, Date hcModifiedOn,
			String hcModifiedBy) {
		this.hotelDetail = hotelDetail;
		this.hcContactName1 = hcContactName1;
		this.hcPosition1 = hcPosition1;
		this.hcPhone1 = hcPhone1;
		this.hcEmail1 = hcEmail1;
		this.hcContactName2 = hcContactName2;
		this.hcPosition2 = hcPosition2;
		this.hcPhone2 = hcPhone2;
		this.hcEmail2 = hcEmail2;
		this.hcIsactive = hcIsactive;
		this.hcModifiedOn = hcModifiedOn;
		this.hcModifiedBy = hcModifiedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "hc_seq_id", unique = true, nullable = false)
	public Integer getHcSeqId() {
		return this.hcSeqId;
	}

	public void setHcSeqId(Integer hcSeqId) {
		this.hcSeqId = hcSeqId;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hc_hd_seq_id", nullable = false)*/
	@Column(name = "hc_hd_seq_id", nullable = false)
	public int getHotelDetail() {
		return this.hotelDetail;
	}

	public void setHotelDetail(int hotelDetail) {
		this.hotelDetail = hotelDetail;
	}

	@Column(name = "hc_contact_name1", nullable = false, length = 30)
	public String getHcContactName1() {
		return this.hcContactName1;
	}

	public void setHcContactName1(String hcContactName1) {
		this.hcContactName1 = hcContactName1;
	}

	@Column(name = "hc_position1", length = 30)
	public String getHcPosition1() {
		return this.hcPosition1;
	}

	public void setHcPosition1(String hcPosition1) {
		this.hcPosition1 = hcPosition1;
	}

	@Column(name = "hc_phone1", nullable = false, length = 15)
	public String getHcPhone1() {
		return this.hcPhone1;
	}

	public void setHcPhone1(String hcPhone1) {
		this.hcPhone1 = hcPhone1;
	}

	@Column(name = "hc_email1", nullable = false, length = 50)
	public String getHcEmail1() {
		return this.hcEmail1;
	}

	public void setHcEmail1(String hcEmail1) {
		this.hcEmail1 = hcEmail1;
	}

	@Column(name = "hc_contact_name2", length = 30)
	public String getHcContactName2() {
		return this.hcContactName2;
	}

	public void setHcContactName2(String hcContactName2) {
		this.hcContactName2 = hcContactName2;
	}

	@Column(name = "hc_position2", length = 30)
	public String getHcPosition2() {
		return this.hcPosition2;
	}

	public void setHcPosition2(String hcPosition2) {
		this.hcPosition2 = hcPosition2;
	}

	@Column(name = "hc_phone2", length = 15)
	public String getHcPhone2() {
		return this.hcPhone2;
	}

	public void setHcPhone2(String hcPhone2) {
		this.hcPhone2 = hcPhone2;
	}

	@Column(name = "hc_email2", length = 50)
	public String getHcEmail2() {
		return this.hcEmail2;
	}

	public void setHcEmail2(String hcEmail2) {
		this.hcEmail2 = hcEmail2;
	}

	@Column(name = "hc_isactive", nullable = false, length = 1)
	public String getHcIsactive() {
		return this.hcIsactive;
	}

	public void setHcIsactive(String hcIsactive) {
		this.hcIsactive = hcIsactive;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hc_modified_on", nullable = false, length = 0)
	public Date getHcModifiedOn() {
		return this.hcModifiedOn;
	}

	public void setHcModifiedOn(Date hcModifiedOn) {
		this.hcModifiedOn = hcModifiedOn;
	}

	@Column(name = "hc_modified_by", nullable = false, length = 30)
	public String getHcModifiedBy() {
		return this.hcModifiedBy;
	}

	public void setHcModifiedBy(String hcModifiedBy) {
		this.hcModifiedBy = hcModifiedBy;
	}

}
