package com.rave.visiit.entity;
// default package
// Generated 30 Dec, 2014 2:39:28 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.rave.visiit.util.Constants;

/**
 * HotelDetail generated by hbm2java
 */
@Entity
@Table(name = "hotel_detail", catalog = Constants.DB_CATELOG)
public class Hotel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer hdSeqId;
	private String hdCode;
	private String hdName;
	private String hdPhone;
	private String hdEmail;
	private String hdAddress;
	private String hdCity;
	private String hdState;
	private String hdCountry;
	private String hdFax;
	private boolean hdWifi;
	private boolean hdGym;
	private boolean hafHelthclubYoga;
	private boolean hdSwimmingpool;
	private boolean hdParking;
	private boolean hdTransfer;
	private Integer hdRating;
	private String hdImage;
	private String hdcategory;
	private String hdReview;
	private Boolean hdIsactive = Boolean.TRUE;
	private String hdDescription;
	private Date hdModifiedOn;
	private String hdModifiedBy;
	@Transient
	private HotelContact hotelContacts = new HotelContact();
	private String hdPostel;
	private boolean hdBar;
	private boolean hdFood;
	private String hdType;
	private String hdStatus;
	private String imageUrl;
	private String iconUrl;
	private Boolean isDeleted = Boolean.FALSE;
	@Transient
	private String activeModel;
	private String reviewCode;
	private Boolean hdAirCondition = Boolean.FALSE;
	private Boolean hdDoctorOnCall = Boolean.FALSE;
	private Boolean hdlaundry = Boolean.FALSE;
	private Boolean hdLibrary = Boolean.FALSE;
	private Boolean hdSPA = Boolean.FALSE;
	private Boolean hdTravelDesk = Boolean.FALSE;
	private Boolean hdTVDVD = Boolean.FALSE;
	private Boolean hdBussinessCenter = Boolean.FALSE;
	private Boolean hdHeater = Boolean.FALSE;
	private Boolean hdIroning = Boolean.FALSE;
	private Boolean hdKids = Boolean.FALSE;
	private Boolean hdDialphone = Boolean.FALSE;
	private Boolean hdRoomsafe = Boolean.FALSE;
	private Boolean hdVilla = Boolean.FALSE;
	private Boolean hdShower = Boolean.FALSE;
	private Boolean hdPickup = Boolean.FALSE;
	private Boolean hdFloralRequest = Boolean.FALSE;
	public Hotel() {
	}

	public Hotel(String hdCode, String hdName, String hdPhone,Boolean hdAirCondition,Boolean hdDoctorOnCall,Boolean hdlaundry,Boolean hdSPA,Boolean hdTravelDesk,Boolean hdTVDVD,
			String hdEmail, String hdAddress, String hdCity, String hdState,Boolean hdBussinessCenter,Boolean hdHeater,Boolean hdShower,Boolean hdPickup,Boolean hdFloralRequest,
			String hdCountry, String hdcategory, Boolean hdIsactive,Boolean hdIroning,Boolean hdKids,Boolean hdDialphone,Boolean hdRoomsafe,Boolean hdVilla,
			String hdDescription, Date hdModifiedOn, String hdModifiedBy,String hdType,String hdStatus,String imageUrl,String iconUrl,Boolean isDeleted,String reviewCode) {
		this.hdCode = hdCode;
		this.hdName = hdName;
		this.hdPhone = hdPhone;
		this.hdEmail = hdEmail;
		this.hdAddress = hdAddress;
		this.hdCity = hdCity;
		this.hdState = hdState;
		this.hdCountry = hdCountry;
		this.hdcategory = hdcategory;
		this.hdIsactive = hdIsactive;
		this.hdDescription = hdDescription;
		this.hdModifiedOn = hdModifiedOn;
		this.hdModifiedBy = hdModifiedBy;
		this.hdType = hdType;
		this.hdStatus = hdStatus;
		this.iconUrl = iconUrl;
		this.imageUrl = imageUrl;
		this.isDeleted = isDeleted;
		this.reviewCode = reviewCode;
		this.hdAirCondition = hdAirCondition;
		this.hdDoctorOnCall = hdDoctorOnCall;
		this.hdlaundry = hdlaundry;
		this.hdSPA = hdSPA;
		this.hdTravelDesk = hdTravelDesk;
		this.hdTVDVD =  hdTVDVD;
		this.hdBussinessCenter = hdBussinessCenter;
		this.hdHeater = hdHeater;
		this.hdIroning = hdIroning;
		this.hdKids = hdKids;
		this.hdDialphone = hdDialphone;
		this.hdRoomsafe = hdRoomsafe;
		this.hdVilla = hdVilla;
		this.hdShower = hdShower;
		this.hdPickup = hdPickup;
		this.hdFloralRequest = hdFloralRequest;
	}

	public Hotel(String hdCode, String hdName, String hdPhone,Boolean hdAirCondition,Boolean hdDoctorOnCall,Boolean hdlaundry,Boolean hdSPA,Boolean hdTravelDesk,Boolean hdTVDVD,
			String hdEmail, String hdAddress, String hdCity, String hdState,Boolean hdBussinessCenter,Boolean hdHeater,Boolean hdShower,Boolean hdPickup,Boolean hdFloralRequest,
			String hdCountry, String hdFax, boolean hdWifi, boolean hdGym,Boolean hdIroning,Boolean hdKids,Boolean hdDialphone,Boolean hdRoomsafe,Boolean hdVilla,
			boolean hafHelthclubYoga, boolean hdSwimmingpool, boolean hdParking,
			boolean hdTransfer, Integer hdRating, String hdImage,
			String hdcategory, String hdReview, Boolean hdIsactive,
			String hdDescription, Date hdModifiedOn, String hdModifiedBy,
			HotelContact hotelContacts,String hdType,String hdStatus,String imageUrl,String iconUrl,Boolean isDeleted,String reviewCode) {
		this.hdCode = hdCode;
		this.hdName = hdName;
		this.hdPhone = hdPhone;
		this.hdEmail = hdEmail;
		this.hdAddress = hdAddress;
		this.hdCity = hdCity;
		this.hdState = hdState;
		this.hdCountry = hdCountry;
		this.hdFax = hdFax;
		this.hdWifi = hdWifi;
		this.hdGym = hdGym;
		this.hafHelthclubYoga = hafHelthclubYoga;
		this.hdSwimmingpool = hdSwimmingpool;
		this.hdParking = hdParking;
		this.hdTransfer = hdTransfer;
		this.hdRating = hdRating;
		this.hdImage = hdImage;
		this.hdcategory = hdcategory;
		this.hdReview = hdReview;
		this.hdIsactive = hdIsactive;
		this.hdDescription = hdDescription;
		this.hdModifiedOn = hdModifiedOn;
		this.hdModifiedBy = hdModifiedBy;
		//this.hotelContacts = hotelContacts;
		this.hdType = hdType;
		this.hdStatus = hdStatus;
		this.iconUrl = iconUrl;
		this.imageUrl = imageUrl;
		this.isDeleted = isDeleted;
		this.reviewCode = reviewCode;
		this.hdAirCondition = hdAirCondition;
		this.hdDoctorOnCall = hdDoctorOnCall;
		this.hdlaundry = hdlaundry;
		this.hdSPA = hdSPA;
		this.hdTravelDesk = hdTravelDesk;
		this.hdTVDVD =  hdTVDVD;
		this.hdBussinessCenter = hdBussinessCenter;
		this.hdHeater = hdHeater;
		this.hdIroning = hdIroning;
		this.hdKids = hdKids;
		this.hdDialphone = hdDialphone;
		this.hdRoomsafe = hdRoomsafe;
		this.hdVilla = hdVilla;
		this.hdShower = hdShower;
		this.hdPickup = hdPickup;
		this.hdFloralRequest = hdFloralRequest;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "hd_seq_id", unique = true, nullable = false)
	public Integer getHdSeqId() {
		return this.hdSeqId;
	}

	public void setHdSeqId(Integer hdSeqId) {
		this.hdSeqId = hdSeqId;
	}

	@Column(name = "hd_code", nullable = false, length = 30)
	public String getHdCode() {
		return this.hdCode;
	}

	public void setHdCode(String hdCode) {
		this.hdCode = hdCode;
	}

	@Column(name = "hd_name", nullable = false, length = 50)
	public String getHdName() {
		return this.hdName;
	}

	public void setHdName(String hdName) {
		this.hdName = hdName;
	}

	@Column(name = "hd_phone", nullable = false, length = 20)
	public String getHdPhone() {
		return this.hdPhone;
	}

	public void setHdPhone(String hdPhone) {
		this.hdPhone = hdPhone;
	}

	@Column(name = "hd_email", nullable = false, length = 50)
	public String getHdEmail() {
		return this.hdEmail;
	}

	public void setHdEmail(String hdEmail) {
		this.hdEmail = hdEmail;
	}

	@Column(name = "hd_address", nullable = false, length = 100)
	public String getHdAddress() {
		return this.hdAddress;
	}

	public void setHdAddress(String hdAddress) {
		this.hdAddress = hdAddress;
	}

	@Column(name = "hd_city", nullable = false, length = 30)
	public String getHdCity() {
		return this.hdCity;
	}

	public void setHdCity(String hdCity) {
		this.hdCity = hdCity;
	}

	@Column(name = "hd_state", nullable = false, length = 30)
	public String getHdState() {
		return this.hdState;
	}

	public void setHdState(String hdState) {
		this.hdState = hdState;
	}

	@Column(name = "hd_country", nullable = false, length = 30)
	public String getHdCountry() {
		return this.hdCountry;
	}

	public void setHdCountry(String hdCountry) {
		this.hdCountry = hdCountry;
	}

	@Column(name = "hd_fax", length = 15)
	public String getHdFax() {
		return this.hdFax;
	}

	public void setHdFax(String hdFax) {
		this.hdFax = hdFax;
	}

	@Column(name = "hd_rating")
	public Integer getHdRating() {
		return this.hdRating;
	}

	public void setHdRating(Integer hdRating) {
		this.hdRating = hdRating;
	}

	@Column(name = "hd_image", length = 50)
	public String getHdImage() {
		return this.hdImage;
	}

	public void setHdImage(String hdImage) {
		this.hdImage = hdImage;
	}

	@Column(name = "hd_category", length = 30)
	public String getHdCategory() {
		return this.hdcategory;
	}

	public void setHdCategory(String hdcategory) {
		this.hdcategory = hdcategory;
	}

	@Column(name = "hd_review", length = 100)
	public String getHdReview() {
		return this.hdReview;
	}

	public void setHdReview(String hdReview) {
		this.hdReview = hdReview;
	}

	@Column(name = "hd_is_active", nullable = false, length = 6)
	public Boolean getHdIsactive() {
		return this.hdIsactive;
	}

	public void setHdIsactive(Boolean hdIsactive) {
		this.hdIsactive = hdIsactive;
	}

	@Column(name = "hd_description", length = 500)
	public String gethdDescription() {
		return this.hdDescription;
	}

	public void sethdDescription(String hdDescription) {
		this.hdDescription = hdDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hd_modified_on", nullable = false, length = 0)
	public Date getHdModifiedOn() {
		return this.hdModifiedOn;
	}

	public void setHdModifiedOn(Date hdModifiedOn) {
		this.hdModifiedOn = hdModifiedOn;
	}

	@Column(name = "hd_modified_by", nullable = false, length = 30)
	public String getHdModifiedBy() {
		return this.hdModifiedBy;
	}

	public void setHdModifiedBy(String hdModifiedBy) {
		this.hdModifiedBy = hdModifiedBy;
	}
	@Transient
	public HotelContact getHotelContacts() {
		return this.hotelContacts;
	}

	public void setHotelContacts(HotelContact hotelContacts) {
		this.hotelContacts = hotelContacts;
	}
		
	@Column(name = "hd_wifi", length = 6)
	public boolean isHdWifi() {
		return hdWifi;
	}

	public void setHdWifi(boolean hdWifi) {
		this.hdWifi = hdWifi;
	}
	
	@Column(name = "hd_gym", length = 6)
	public boolean isHdGym() {
		return hdGym;
	}

	public void setHdGym(boolean hdGym) {
		this.hdGym = hdGym;
	}
	
	@Column(name = "haf_helthclub_yoga", length = 6)
	public boolean isHafHelthclubYoga() {
		return hafHelthclubYoga;
	}
	
	
	public void setHafHelthclubYoga(boolean hafHelthclubYoga) {
		this.hafHelthclubYoga = hafHelthclubYoga;
	}
	
	@Column(name = "hd_swimmingpool", length = 6)
	public boolean isHdSwimmingpool() {
		return hdSwimmingpool;
	}
	
	public void setHdSwimmingpool(boolean hdSwimmingpool) {
		this.hdSwimmingpool = hdSwimmingpool;
	}
	
	@Column(name = "hd_parking", length = 6)
	public boolean isHdParking() {
		return hdParking;
	}

	public void setHdParking(boolean hdParking) {
		this.hdParking = hdParking;
	}
	
	@Column(name = "hd_transfer", length = 15)
	public boolean isHdTransfer() {
		return hdTransfer;
	}

	public void setHdTransfer(boolean hdTransfer) {
		this.hdTransfer = hdTransfer;
	}
	
	@Column(name = "hd_postal_code", length = 10)
	public String getHdPostel() {
		return hdPostel;
	}

	public void setHdPostel(String hdPostel) {
		this.hdPostel = hdPostel;
	}
	
	@Column(name = "hd_bar", length = 6)
	public boolean isHdBar() {
		return hdBar;
	}

	public void setHdBar(boolean hdBar) {
		this.hdBar = hdBar;
	}
	
	@Column(name = "hd_food", length = 6)
	public boolean isHdFood() {
		return hdFood;
	}

	public void setHdFood(boolean hdFood) {
		this.hdFood = hdFood;
	}
	
	@Column(name = "hd_type",length = 50)
	public String getHdType() {
		return hdType;
	}
	
	public void setHdType(String hdType) {
		this.hdType = hdType;
	}
	
	@Column(name = "hd_status")
	public String getHdStatus() {
		return hdStatus;
	}

	public void setHdStatus(String hdStatus) {
		this.hdStatus = hdStatus;
	}
	
/*	@Column(name = "img_url",length=255)
	public String getImgUrl() {
		return imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		if(imgUrl != null){
			this.imgUrl = imgUrl.replace("\\", "/");
		}else{this.imgUrl = imgUrl;}
		//this.imgUrl = imgUrl;
	}*/
	
	@Column(name = "icon_url",length=255)
	public String getIconUrl() {
		return iconUrl;
	}

	public void setIconUrl(String iconUrl) {
		this.iconUrl = iconUrl;
	}
	
	@Column(name = "image_url",length=255)
	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		if(imageUrl != null){
			this.imageUrl = imageUrl.replace("\\", "/");
		}else{this.imageUrl = imageUrl;}
	}
	
	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}
	@Transient
	public String getActiveModel() {
		if(hdIsactive != null && hdIsactive){
			this.activeModel = "Y";
		} else {
			this.activeModel = "N";
		}
		return activeModel;
	}

	public void setActiveModel(String activeModel) {
		this.activeModel = activeModel;
	}
	
	@Column(name = "review_code",length=30)
	public String getReviewCode() {
		return reviewCode;
	}

	public void setReviewCode(String reviewCode) {
		this.reviewCode = reviewCode;
	}
	
	@Column(name = "air_conditions", length = 6)
	public Boolean getHdAirCondition() {
		return hdAirCondition;
	}

	public void setHdAirCondition(Boolean hdAirCondition) {
		this.hdAirCondition = hdAirCondition;
	}
	
	@Column(name = "doctor_on_call", length = 6)
	public Boolean getHdDoctorOnCall() {
		return hdDoctorOnCall;
	}

	public void setHdDoctorOnCall(Boolean hdDoctorOnCall) {
		this.hdDoctorOnCall = hdDoctorOnCall;
	}
	
	@Column(name = "laundry", length = 6)
	public Boolean getHdlaundry() {
		return hdlaundry;
	}

	public void setHdlaundry(Boolean hdlaundry) {
		this.hdlaundry = hdlaundry;
	}
	
	@Column(name = "library", length = 6)
	public Boolean getHdLibrary() {
		return hdLibrary;
	}

	public void setHdLibrary(Boolean hdLibrary) {
		this.hdLibrary = hdLibrary;
	}
	
	@Column(name = "spa", length = 6)
	public Boolean getHdSPA() {
		return hdSPA;
	}

	public void setHdSPA(Boolean hdSPA) {
		this.hdSPA = hdSPA;
	}
	
	@Column(name = "travel_desk", length = 6)
	public Boolean getHdTravelDesk() {
		return hdTravelDesk;
	}

	public void setHdTravelDesk(Boolean hdTravelDesk) {
		this.hdTravelDesk = hdTravelDesk;
	}
	
	@Column(name = "tv_dvd", length = 6)
	public Boolean getHdTVDVD() {
		return hdTVDVD;
	}

	public void setHdTVDVD(Boolean hdTVDVD) {
		this.hdTVDVD = hdTVDVD;
	}

	@Column(name = "bussiness_center", length = 6)
	public Boolean getHdBussinessCenter() {
		return hdBussinessCenter;
	}

	public void setHdBussinessCenter(Boolean hdBussinessCenter) {
		this.hdBussinessCenter = hdBussinessCenter;
	}
	
	@Column(name = "heater", length = 6)
	public Boolean getHdHeater() {
		return hdHeater;
	}

	public void setHdHeater(Boolean hdHeater) {
		this.hdHeater = hdHeater;
	}
	
	@Column(name = "ironing", length = 6)
	public Boolean getHdIroning() {
		return hdIroning;
	}

	public void setHdIroning(Boolean hdIroning) {
		this.hdIroning = hdIroning;
	}
	
	@Column(name = "kids", length = 6)
	public Boolean getHdKids() {
		return hdKids;
	}

	public void setHdKids(Boolean hdKids) {
		this.hdKids = hdKids;
	}
	
	@Column(name = "dial_phone", length = 6)
	public Boolean getHdDialphone() {
		return hdDialphone;
	}

	public void setHdDialphone(Boolean hdDialphone) {
		this.hdDialphone = hdDialphone;
	}
	
	@Column(name = "room_safe", length = 6)
	public Boolean getHdRoomsafe() {
		return hdRoomsafe;
	}

	public void setHdRoomsafe(Boolean hdRoomsafe) {
		this.hdRoomsafe = hdRoomsafe;
	}
	
	@Column(name = "villa", length = 6)
	public Boolean getHdVilla() {
		return hdVilla;
	}

	public void setHdVilla(Boolean hdVilla) {
		this.hdVilla = hdVilla;
	}
	
	@Column(name = "shower", length = 6)
	public Boolean getHdShower() {
		return hdShower;
	}

	public void setHdShower(Boolean hdShower) {
		this.hdShower = hdShower;
	}
	
	@Column(name = "pickup", length = 6)
	public Boolean getHdPickup() {
		return hdPickup;
	}

	public void setHdPickup(Boolean hdPickup) {
		this.hdPickup = hdPickup;
	}
	
	@Column(name = "floral_request", length = 6)
	public Boolean getHdFloralRequest() {
		return hdFloralRequest;
	}

	public void setHdFloralRequest(Boolean hdFloralRequest) {
		this.hdFloralRequest = hdFloralRequest;
	}
	
}
