package com.rave.visiit.entity;
// default package
// Generated 30 Jan, 2015 2:51:33 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.rave.visiit.util.Constants;

/**
 * Locations generated by hbm2java
 */
@Entity
@Table(name = "locations", catalog = Constants.DB_CATELOG)
public class Locations implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer locId;
	private int city;
	private String locCode;
	private String locName;
	private String locDescription;
	private Boolean locIsactive;
	private Date locUpdatedDate;
	private Boolean isDeleted = Boolean.FALSE;
	@Transient
	private String activeModel;
	private String reviewCode;
	private String modifiedBy;
	private Date createdOn;
	private String createdBy;
	
	public Locations() {
	}

	public Locations(int city, String locCode, String locName,
			String locDescription, Boolean locIsactive,
			Date locUpdatedDate,Boolean isDeleted,String reviewCode) {
		this.city = city;
		this.locCode = locCode;
		this.locName = locName;
		this.locDescription = locDescription;
		this.locIsactive = locIsactive;
		this.locUpdatedDate = locUpdatedDate;
		this.reviewCode = reviewCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "loc_id", unique = true, nullable = false)
	public Integer getLocId() {
		return this.locId;
	}

	public void setLocId(Integer locId) {
		this.locId = locId;
	}

//	@ManyToOne(fetch = FetchType.EAGER)
//	@JoinColumn(name = "loc_city_id", nullable = false)
	//@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE_ORPHAN})
	@Column(name = "loc_city_id", nullable = false)
	public int getCity() {
		return this.city;
	}

	public void setCity(int city) {
		this.city = city;
	}

	@Column(name = "loc_code", nullable = false, length = 30)
	public String getLocCode() {
		return this.locCode;
	}

	public void setLocCode(String locCode) {
		this.locCode = locCode;
	}

	@Column(name = "loc_name", nullable = false, length = 50)
	public String getLocName() {
		return this.locName;
	}

	public void setLocName(String locName) {
		this.locName = locName;
	}

	@Column(name = "loc_description", length = 100)
	public String getLocDescription() {
		return this.locDescription;
	}

	public void setLocDescription(String locDescription) {
		this.locDescription = locDescription;
	}

	@Column(name = "loc_is_active", nullable = false, length = 6)
	public Boolean getLocIsactive() {
		return this.locIsactive;
	}

	public void setLocIsactive(Boolean locIsactive) {
		this.locIsactive = locIsactive;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "loc_updated_date", nullable = false, length = 0)
	public Date getLocUpdatedDate() {
		return this.locUpdatedDate;
	}

	public void setLocUpdatedDate(Date locUpdatedDate) {
		this.locUpdatedDate = locUpdatedDate;
	}
	
	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}
	
	@Transient
	public String getActiveModel() {
		if(locIsactive != null && locIsactive){
			this.activeModel = "Y";
		} else {
			this.activeModel = "N";
		}
		return activeModel;
	}

	public void setActiveModel(String activeModel) {
			this.activeModel = activeModel;
	}
	
	@Column(name = "review_code",length=30)
	public String getReviewCode() {
		return reviewCode;
	}

	public void setReviewCode(String reviewCode) {
		this.reviewCode = reviewCode;
	}
	
	@Column(name = "modified_by")
	public String getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 0)
	public Date getCreatedOn() {
		return createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}
	
	@Column(name = "created_by")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
}
