package com.rave.visiit.entity;
// default package
// Generated 24 Dec, 2014 7:54:49 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.rave.visiit.util.Constants;

/**
 * Designation generated by hbm2java
 */
@Entity
@Table(name = "module", catalog = Constants.DB_CATELOG)
public class Module implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1872009784623882820L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "mod_id", unique = true, nullable = false)
	private Integer modId;
	
	@Column(name = "mod_code", nullable = false, length = 30)
	private String modCode;
	
	@Column(name = "mod_name", nullable = false, length = 50)
	private String modName;

	@Column(name = "mod_description", length = 100)
	private String modDescription;
	
	@Column(name = "mod_is_active")
	private boolean modIsActive = true;
	
	@Column(name = "is_deleted")
	private boolean isDeleted = false;
	
	@Column(name = "parent_id")
	private Integer parentId;

	public Integer getModId() {
		return modId;
	}

	public void setModId(Integer modId) {
		this.modId = modId;
	}

	public String getModCode() {
		return modCode;
	}

	public void setModCode(String modCode) {
		this.modCode = modCode;
	}

	public String getModName() {
		return modName;
	}

	public void setModName(String modName) {
		this.modName = modName;
	}

	public String getModDescription() {
		return modDescription;
	}

	public void setModDescription(String modDescription) {
		this.modDescription = modDescription;
	}

	public boolean isModIsActive() {
		return modIsActive;
	}

	public void setModIsActive(boolean modIsActive) {
		this.modIsActive = modIsActive;
	}

	public boolean isDeleted() {
		return isDeleted;
	}

	public void setDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}
	
}
