package com.rave.visiit.entity;
// default package
// Generated 29 Dec, 2014 3:09:30 PM by Hibernate Tools 3.4.0.CR1


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.rave.visiit.util.Constants;

/**
 * PackageAttractions generated by hbm2java
 */
@Entity
@Table(name="package_attractions"
    ,catalog=Constants.DB_CATELOG
)
public class PackageAttraction  implements java.io.Serializable {


     private Integer pkaSeqId;
     private Package pack;
     private String pkaAttaction;
     private String pkaDescription;
     private int pkaRating;
     private String pkaIsactive;
     private String pkaFilePath;
     private Date pkaModifiedOn;
     private String pkaModifiedBy;
     private String pkaType;

    public PackageAttraction() {
    }

	
    public PackageAttraction(Package pack, String pkaAttaction, String pkaDescription, int pkaRating, String pkaIsactive, Date pkaModifiedOn, String pkaModifiedBy,String pkaType) {
        this.pack = pack;
        this.pkaAttaction = pkaAttaction;
        this.pkaDescription = pkaDescription;
        this.pkaRating = pkaRating;
        this.pkaIsactive = pkaIsactive;
        this.pkaModifiedOn = pkaModifiedOn;
        this.pkaModifiedBy = pkaModifiedBy;
        this.pkaType = pkaType;
    }
    public PackageAttraction(Package pack, String pkaAttaction, String pkaDescription, int pkaRating, String pkaIsactive, String pkaFilePath, Date pkaModifiedOn, String pkaModifiedBy,String pkaType) {
       this.pack = pack;
       this.pkaAttaction = pkaAttaction;
       this.pkaDescription = pkaDescription;
       this.pkaRating = pkaRating;
       this.pkaIsactive = pkaIsactive;
       this.pkaFilePath = pkaFilePath;
       this.pkaModifiedOn = pkaModifiedOn;
       this.pkaModifiedBy = pkaModifiedBy;
       this.pkaType =pkaType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="pka_seq_id", unique=true, nullable=false)
    public Integer getPkaSeqId() {
        return this.pkaSeqId;
    }
    
    public void setPkaSeqId(Integer pkaSeqId) {
        this.pkaSeqId = pkaSeqId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pka_pk_id", nullable=false)
    public Package getPackage() {
        return this.pack;
    }
    
    public void setPackage(Package pack) {
        this.pack = pack;
    }

    
    @Column(name="pka_attaction", nullable=false, length=100)
    public String getPkaAttaction() {
        return this.pkaAttaction;
    }
    
    public void setPkaAttaction(String pkaAttaction) {
        this.pkaAttaction = pkaAttaction;
    }

    
    @Column(name="pka_description", nullable=false, length=500)
    public String getPkaDescription() {
        return this.pkaDescription;
    }
    
    public void setPkaDescription(String pkaDescription) {
        this.pkaDescription = pkaDescription;
    }

    
    @Column(name="pka_rating", nullable=false)
    public int getPkaRating() {
        return this.pkaRating;
    }
    
    public void setPkaRating(int pkaRating) {
        this.pkaRating = pkaRating;
    }

    
    @Column(name="pka_isactive", nullable=false, length=1)
    public String getPkaIsactive() {
        return this.pkaIsactive;
    }
    
    public void setPkaIsactive(String pkaIsactive) {
        this.pkaIsactive = pkaIsactive;
    }

    
    @Column(name="pka_file_path", length=300)
    public String getPkaFilePath() {
        return this.pkaFilePath;
    }
    
    public void setPkaFilePath(String pkaFilePath) {
        this.pkaFilePath = pkaFilePath;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="pka_modified_on", nullable=false, length=0)
    public Date getPkaModifiedOn() {
        return this.pkaModifiedOn;
    }
    
    public void setPkaModifiedOn(Date pkaModifiedOn) {
        this.pkaModifiedOn = pkaModifiedOn;
    }

    
    @Column(name="pka_modified_by", nullable=false, length=30)
    public String getPkaModifiedBy() {
        return this.pkaModifiedBy;
    }
    
    public void setPkaModifiedBy(String pkaModifiedBy) {
        this.pkaModifiedBy = pkaModifiedBy;
    }

    @Column(name="pka_type", length=30)
	public String getPkaType() {
		return pkaType;
	}
	
	public void setPkaType(String pkaType) {
		this.pkaType = pkaType;
	}

    


}


