package com.rave.visiit.entity;

// default package
// Generated 29 Dec, 2014 3:09:30 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.rave.visiit.util.Constants;

/**
 * PackageInclusion generated by hbm2java
 */
@Entity
@Table(name = "package_inclusion", catalog = Constants.DB_CATELOG)
public class PackageInclusion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer pkinSeqId;
	private Package pack;
	private String pkinDescription;
	private Boolean pkinStatus = Boolean.TRUE;
	private Date pkinModifiedOn;
	private String pkinModifiedBy;
	private Boolean pkinActive = Boolean.TRUE;
	private Boolean isDeleted = Boolean.FALSE;
	private String imageUrl;
	@Transient
	private String type="Inclusion";

	public PackageInclusion() {
	}

	public PackageInclusion(Package pack, String pkinDescription,
			Boolean pkinStatus, Date pkinModifiedOn, String pkinModifiedBy,
			Boolean pkinActive, String imageUrl,String type) {
		this.pack = pack;
		this.pkinDescription = pkinDescription;
		this.pkinStatus = pkinStatus;
		this.pkinModifiedOn = pkinModifiedOn;
		this.pkinModifiedBy = pkinModifiedBy;
		this.pkinActive = pkinActive;
		this.imageUrl = imageUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pkin_seq_id", unique = true, nullable = false)
	public Integer getPkinSeqId() {
		return this.pkinSeqId;
	}

	public void setPkinSeqId(Integer pkinSeqId) {
		this.pkinSeqId = pkinSeqId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pkin_pk_id", nullable = false)
	public Package getPack() {
		return pack;
	}

	public void setPack(Package pack) {
		this.pack = pack;
	}

	@Column(name = "pkin_description", nullable = false, length = 500)
	public String getPkinDescription() {
		return this.pkinDescription;
	}

	public void setPkinDescription(String pkinDescription) {
		this.pkinDescription = pkinDescription;
	}

	@Column(name = "pkin_status", nullable = false, length = 6)
	public Boolean getPkinStatus() {
		return this.pkinStatus;
	}

	public void setPkinStatus(Boolean pkinStatus) {
		this.pkinStatus = pkinStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pkin_modified_on", nullable = false, length = 0)
	public Date getPkinModifiedOn() {
		return this.pkinModifiedOn;
	}

	public void setPkinModifiedOn(Date pkinModifiedOn) {
		this.pkinModifiedOn = pkinModifiedOn;
	}

	@Column(name = "pkin_modified_by", nullable = false, length = 30)
	public String getPkinModifiedBy() {
		return this.pkinModifiedBy;
	}

	public void setPkinModifiedBy(String pkinModifiedBy) {
		this.pkinModifiedBy = pkinModifiedBy;
	}

	@Column(name = "pkin_active", nullable = false, length = 6)
	public Boolean getPkinActive() {
		return pkinActive;
	}

	public void setPkinActive(Boolean pkinActive) {
		this.pkinActive = pkinActive;
	}
	
	@Column(name = "image_url", length = 500)
	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		if(imageUrl != null){
			this.imageUrl = imageUrl.replace("\\", "/");
		}else{this.imageUrl = imageUrl;}
		//this.imageUrl = imageUrl;
	}
	
	@Transient
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	@Column(name = "is_deleted", nullable = false, length = 6)
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}
	
	
	
}
