package com.rave.visiit.entity;
// default package
// Generated 28 Jan, 2015 7:23:48 PM by Hibernate Tools 3.4.0.CR1


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.rave.visiit.util.Constants;

/**
 * PackageCost generated by hbm2java
 */
@Entity
@Table(name="package_cost"
    ,catalog=Constants.DB_CATELOG
)
public class PackageCost  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer pkcId;
     private Package pack;
     private Integer pkcCost;
     private Date pkcValidFrom;
     private Date pkcValidTo;
     private String pkcDescription;
     private Date pkcModifiedOn;
     private String pkcModifiedBy;
     private Integer validDays;
     //private String active = "true";
     private Boolean isDeleted = Boolean.FALSE;
     private Integer offerPrice;
    public PackageCost() {
    }

	
    public PackageCost(Package pack, Integer pkcCost, String pkcModifiedBy,Integer validDays,Boolean isDeleted,Integer offerPrice) {
        this.pack = pack;
        this.pkcCost = pkcCost;
        this.pkcModifiedBy = pkcModifiedBy;
        this.validDays = validDays;
        this.isDeleted = isDeleted;
        this.offerPrice = offerPrice;
    }
    public PackageCost(Package pack, Integer pkcCost, Date pkcValidFrom, Date pkcValidTo, String pkcDescription, Date pkcModifiedOn, String pkcModifiedBy,Integer validDays,Boolean isDeleted,Integer offerPrice) {
       this.pack = pack;
       this.pkcCost = pkcCost;
       this.pkcValidFrom = pkcValidFrom;
       this.pkcValidTo = pkcValidTo;
       this.pkcDescription = pkcDescription;
       this.pkcModifiedOn = pkcModifiedOn;
       this.pkcModifiedBy = pkcModifiedBy;
       this.validDays = validDays;
       this.isDeleted = isDeleted;
       this.offerPrice = offerPrice;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
     @Column(name="pkc_id", unique=true, nullable=false)
    public Integer getPkcId() {
        return this.pkcId;
    }
    
    public void setPkcId(Integer pkcId) {
        this.pkcId = pkcId;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="pkc_pk_id", nullable=false)
    public Package getPack() {
        return this.pack;
    }
    
    public void setPack(Package pack) {
        this.pack = pack;
    }

    
    @Column(name="pkc_cost", nullable=false,length=7)
    public Integer getPkcCost() {
        return this.pkcCost;
    }
    
    public void setPkcCost(Integer pkcCost) {
        this.pkcCost = pkcCost;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="pkc_valid_from", length=0)
    public Date getPkcValidFrom() {
        return this.pkcValidFrom;
    }
    
    public void setPkcValidFrom(Date pkcValidFrom) {
        this.pkcValidFrom = pkcValidFrom;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="pkc_valid_to", length=0)
    public Date getPkcValidTo() {
        return this.pkcValidTo;
    }
    
    public void setPkcValidTo(Date pkcValidTo) {
        this.pkcValidTo = pkcValidTo;
    }

    
    @Column(name="pkc_description", length=500)
    public String getPkcDescription() {
        return this.pkcDescription;
    }
    
    public void setPkcDescription(String pkcDescription) {
        this.pkcDescription = pkcDescription;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="pkc_modified_on", length=0)
    public Date getPkcModifiedOn() {
        return this.pkcModifiedOn;
    }
    
    public void setPkcModifiedOn(Date pkcModifiedOn) {
        this.pkcModifiedOn = pkcModifiedOn;
    }

    
    @Column(name="pkc_modified_by", nullable=false, length=30)
    public String getPkcModifiedBy() {
        return this.pkcModifiedBy;
    }
    
    public void setPkcModifiedBy(String pkcModifiedBy) {
        this.pkcModifiedBy = pkcModifiedBy;
    }

    @Column(name="pkc_valid_day", length=30)
	public Integer getValidDays() {
		return validDays;
	}
	
	public void setValidDays(Integer validDays) {
		this.validDays = validDays;
	}

	@Column(name="pkc_offer_price")
	public Integer getOfferPrice() {
		return offerPrice;
	}
	public void setOfferPrice(Integer offerPrice) {
		this.offerPrice = offerPrice;
	}

	@Column(name="is_deleted")
	public Boolean getIsDeleted() {
		return isDeleted;
	}


	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}
	
	
}


