package com.rave.visiit.entity;

// default package
// Generated 29 Dec, 2014 3:09:30 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.rave.visiit.util.Constants;

/**
 * PackageExclusion generated by hbm2java
 */
@Entity
@Table(name = "package_exclusion", catalog = Constants.DB_CATELOG)
public class PackageExclusion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8685870507001820792L;
	private Integer pkexSeqId;
	private Package pack;
	private String pkexDescription;
	private Boolean pkexStatus;
	private Date pkexModifiedOn;
	private String pkexModifiedBy;
	private Boolean pkexActive;
	private String imageUrl;
	private Boolean isDeleted = Boolean.FALSE;
	@Transient
	private String type="Exclusion";

	public PackageExclusion() {
		pack = new Package();
	}

	public PackageExclusion(Package pack, String pkexDescription,
			Boolean pkexStatus, Date pkexModifiedOn, String pkexModifiedBy,
			Boolean pkexActive, String imageUrl,String type) {
		this.pack = pack;
		this.pkexDescription = pkexDescription;
		this.pkexStatus = pkexStatus;
		this.pkexModifiedOn = pkexModifiedOn;
		this.pkexModifiedBy = pkexModifiedBy;
		this.pkexActive = pkexActive;
		this.imageUrl = imageUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pkex_seq_id", unique = true, nullable = false)
	public Integer getPkexSeqId() {
		return this.pkexSeqId;
	}

	public void setPkexSeqId(Integer pkexSeqId) {
		this.pkexSeqId = pkexSeqId;
	}

	@Column(name = "pkex_description", nullable = false, length = 500)
	public String getPkexDescription() {
		return this.pkexDescription;
	}

	public void setPkexDescription(String pkexDescription) {
		this.pkexDescription = pkexDescription;
	}

	@Column(name = "pkex_status", nullable = false, length = 1)
	public Boolean getPkexStatus() {
		return this.pkexStatus;
	}

	public void setPkexStatus(Boolean pkexStatus) {
		this.pkexStatus = pkexStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pkex_modified_on", nullable = false, length = 0)
	public Date getPkexModifiedOn() {
		return this.pkexModifiedOn;
	}

	public void setPkexModifiedOn(Date pkexModifiedOn) {
		this.pkexModifiedOn = pkexModifiedOn;
	}

	@Column(name = "pkex_modified_by", nullable = false, length = 30)
	public String getPkexModifiedBy() {
		return this.pkexModifiedBy;
	}

	public void setPkexModifiedBy(String pkexModifiedBy) {
		this.pkexModifiedBy = pkexModifiedBy;
	}

	@Column(name = "pkex_active", nullable = false, length = 1)
	public Boolean getPkexActive() {
		return pkexActive;
	}

	public void setPkexActive(Boolean pkexActive) {
		this.pkexActive = pkexActive;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pkex_pk_id", nullable = false)
	public Package getPack() {
		return pack;
	}

	public void setPack(Package pack) {
		this.pack = pack;
	}
	
	@Column(name = "image_url", length = 500)
	public String getImageUrl() {
		return imageUrl;
	}
	public void setImageUrl(String imageUrl) {
		if(imageUrl != null){
			this.imageUrl = imageUrl.replace("\\", "/");
		}else{this.imageUrl = imageUrl;}
		//this.imageUrl = imageUrl;
	}
	
	@Transient
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
	@Column(name = "is_deleted", nullable = false, length = 6)
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}
	
	
}
