package com.rave.visiit.entity;

// default package
// Generated 29 Dec, 2014 3:09:30 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.rave.visiit.util.Constants;

/**
 * PackageItinerary generated by hbm2java
 */
@Entity
@Table(name = "package_itinerary", catalog = Constants.DB_CATELOG)
public class PackageItinerary implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer pkiSeqId;
	private Package pack;
	private int pkiDay;
	private String pkiItinerary;
	private String pkiDescription;
	private Boolean pkiIsactive = Boolean.TRUE;
	private Date pkiModifiedOn;
	private String pkiModifiedBy;
	private String imageUrl;
	private Boolean isDeleted = Boolean.FALSE;
	private boolean pkFlight;
	private boolean pkHotel;
	private boolean pkFood;
	private boolean pkTrain;
	private boolean pkBus;
	private boolean pkFerry;
	@Transient
	private String activeModel;
	
	private Boolean pkGuide = Boolean.FALSE;
	private Boolean pkJungle = Boolean.FALSE;
	private Boolean pkShows = Boolean.FALSE;
	private Boolean pkSports = Boolean.FALSE;
	private Boolean pkCampfire = Boolean.FALSE;
	private Boolean pkSeaActivity = Boolean.FALSE;
	private Boolean pkPickUp = Boolean.FALSE;
	
	public PackageItinerary() {
	}

	public PackageItinerary(Package pack, int pkiDay, String pkiItinerary,Boolean pkGuide,Boolean pkJungle,Boolean pkShows,Boolean pkSports,Boolean pkCampfire,Boolean pkSeaActivity,Boolean pkPickUp,
			String pkiDescription, Boolean pkiIsactive, String pkiModifiedBy,
			String imageUrl, Boolean isDeleted) {
		this.pack = pack;
		this.pkiDay = pkiDay;
		this.pkiItinerary = pkiItinerary;
		this.pkiDescription = pkiDescription;
		this.pkiIsactive = pkiIsactive;
		this.pkiModifiedBy = pkiModifiedBy;
		this.imageUrl = imageUrl;
		this.isDeleted = isDeleted;
	}

	public PackageItinerary(Package pack, int pkiDay, String pkiItinerary,Boolean pkGuide,Boolean pkJungle,Boolean pkShows,Boolean pkSports,Boolean pkCampfire,Boolean pkSeaActivity,Boolean pkPickUp,
			String pkiDescription, Boolean pkiIsactive, Date pkiModifiedOn,
			String pkiModifiedBy, String imageUrl, Boolean isDeleted) {
		this.pack = pack;
		this.pkiDay = pkiDay;
		this.pkiItinerary = pkiItinerary;
		this.pkiDescription = pkiDescription;
		this.pkiIsactive = pkiIsactive;
		this.pkiModifiedOn = pkiModifiedOn;
		this.pkiModifiedBy = pkiModifiedBy;
		this.imageUrl = imageUrl;
		this.isDeleted = isDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pki_seq_id", unique = true, nullable = false)
	public Integer getPkiSeqId() {
		return this.pkiSeqId;
	}

	public void setPkiSeqId(Integer pkiSeqId) {
		this.pkiSeqId = pkiSeqId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pki_pk_id", nullable = false)
	public Package getPack() {
		return this.pack;
	}

	public void setPack(Package pack) {
		this.pack = pack;
	}

	@Column(name = "pki_day", nullable = false)
	public int getPkiDay() {
		return this.pkiDay;
	}

	public void setPkiDay(int pkiDay) {
		this.pkiDay = pkiDay;
	}

	@Column(name = "pki_itinerary", nullable = false, length = 500)
	public String getPkiItinerary() {
		return this.pkiItinerary;
	}

	public void setPkiItinerary(String pkiItinerary) {
		this.pkiItinerary = pkiItinerary;
	}

	@Column(name = "pki_description", length = 500)
	public String getPkiDescription() {
		return this.pkiDescription;
	}

	public void setPkiDescription(String pkiDescription) {
		this.pkiDescription = pkiDescription;
	}

	@Column(name = "pki_is_active", nullable = false, length = 6)
	public Boolean getPkiIsactive() {
		return this.pkiIsactive;
	}

	public void setPkiIsactive(Boolean pkiIsactive) {
		this.pkiIsactive = pkiIsactive;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pki_modified_on", length = 0)
	public Date getPkiModifiedOn() {
		return this.pkiModifiedOn;
	}

	public void setPkiModifiedOn(Date pkiModifiedOn) {
		this.pkiModifiedOn = pkiModifiedOn;
	}

	@Column(name = "pki_modified_by", nullable = false, length = 30)
	public String getPkiModifiedBy() {
		return this.pkiModifiedBy;
	}

	public void setPkiModifiedBy(String pkiModifiedBy) {
		this.pkiModifiedBy = pkiModifiedBy;
	}

	@Column(name = "image_url", length = 255)
	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "pki_flight")
	public boolean isPkFlight() {
		return pkFlight;
	}

	public void setPkFlight(boolean pkFlight) {
		this.pkFlight = pkFlight;
	}

	@Column(name = "pki_hotel")
	public boolean isPkHotel() {
		return pkHotel;
	}

	public void setPkHotel(boolean pkHotel) {
		this.pkHotel = pkHotel;
	}

	@Column(name = "pki_food")
	public boolean isPkFood() {
		return pkFood;
	}

	public void setPkFood(boolean pkFood) {
		this.pkFood = pkFood;
	}

	@Column(name = "pki_train")
	public boolean isPkTrain() {
		return pkTrain;
	}

	public void setPkTrain(boolean pkTrain) {
		this.pkTrain = pkTrain;
	}

	@Column(name = "pki_bus")
	public boolean isPkBus() {
		return pkBus;
	}

	public void setPkBus(boolean pkBus) {
		this.pkBus = pkBus;
	}

	@Column(name = "pki_ferry")
	public boolean isPkFerry() {
		return pkFerry;
	}

	public void setPkFerry(boolean pkFerry) {
		this.pkFerry = pkFerry;
	}
	
	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}
	
	@Transient
	public String getActiveModel() {
		if(pkiIsactive != null && pkiIsactive){
			this.activeModel = "Y";
		} else {
			this.activeModel = "N";
		}
		return activeModel;
	}

	public void setActiveModel(String activeModel) {
		this.activeModel = activeModel;
	}
	
	@Column(name = "pki_guide")
	public Boolean getPkGuide() {
		return pkGuide;
	}

	public void setPkGuide(Boolean pkGuide) {
		this.pkGuide = pkGuide;
	}
	
	@Column(name = "pki_jungle")
	public Boolean getPkJungle() {
		return pkJungle;
	}

	public void setPkJungle(Boolean pkJungle) {
		this.pkJungle = pkJungle;
	}
	
	@Column(name = "pki_shows")
	public Boolean getPkShows() {
		return pkShows;
	}

	public void setPkShows(Boolean pkShows) {
		this.pkShows = pkShows;
	}
	
	@Column(name = "pki_sports")
	public Boolean getPkSports() {
		return pkSports;
	}

	public void setPkSports(Boolean pkSports) {
		this.pkSports = pkSports;
	}
	
	@Column(name = "pki_camp_fire")
	public Boolean getPkCampfire() {
		return pkCampfire;
	}

	public void setPkCampfire(Boolean pkCampfire) {
		this.pkCampfire = pkCampfire;
	}
	
	@Column(name = "pki_sea_activity")
	public Boolean getPkSeaActivity() {
		return pkSeaActivity;
	}

	public void setPkSeaActivity(Boolean pkSeaActivity) {
		this.pkSeaActivity = pkSeaActivity;
	}
	@Column(name = "pki_pickup")
	public Boolean getPkPickUp() {
		return pkPickUp;
	}

	public void setPkPickUp(Boolean pkPickUp) {
		this.pkPickUp = pkPickUp;
	}
	
	
	
}
