package com.rave.visiit.entity;
// default package
// Generated 29 Dec, 2014 3:09:30 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.rave.visiit.util.Constants;

/**
 * Package generated by hbm2java
 */
@Entity
@Table(name = "package", catalog = Constants.DB_CATELOG)
public class Package implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer pkId;
	private Category category;
	private Vendor vendorInformation;
	private String pkCode;
	private String pkName;
	private String pkPlace;
	private BigDecimal pkCost;
	private String pkIsFlexible;        
	private Integer pkType;
	private Integer pkRating;
	private Integer pkDays;
	private Integer pkNights;
	private Boolean pkFlight = Boolean.TRUE;
	private Boolean pkHotel = Boolean.TRUE;
	private Boolean pkFood = Boolean.TRUE;
	private Boolean pkTrain = Boolean.TRUE;
	private Boolean pkBus = Boolean.TRUE;
	private Boolean pkFerry = Boolean.TRUE;
	private Boolean pkVisaFeeInclusion = Boolean.TRUE;
	private Boolean pkTransfer = Boolean.FALSE;
	private Integer pkDistance;
	private Date pkValidFrom;
	private Date pkValidTo;
	private Boolean pkIsactive = Boolean.TRUE;
	private String pkFilePath;
	private String pkDescripton;
	private Date pkModifiedOn;
	private String pkModifiedBy;
	private Boolean isDeleted = Boolean.FALSE;
	private boolean pkPrice;
	private boolean pkActivity;
	private boolean pkHotels;
	private String imageUrl;
	private String tileImageUrl;
	private String pkSpecial;
	private Integer pkOrder;
	@Transient
	private String activeModel;
	@Transient
	private String pkFlightModel;
	@Transient
	private String pkHotelModel;
	@Transient
	private String pkFoodModel;
	@Transient
	private String pkTrainModel;
	@Transient
	private String pkBusModel;
	@Transient
	private String pkFerryModel;
	@Transient
	private String pkVisaFeeInclusionModel;
	@Transient
	private String pkTransferModel;
	private Boolean isValid = Boolean.FALSE;
	private Boolean pkGuide = Boolean.FALSE;
	private Boolean pkJungle = Boolean.FALSE;
	private Boolean pkShows = Boolean.FALSE;
	private Boolean pkSports = Boolean.FALSE;
	private Boolean pkCampfire = Boolean.FALSE;
	private Boolean pkSeaActivity = Boolean.FALSE;
	private Boolean pkPickUp = Boolean.FALSE;
	public Package() {
	}

	public Package(Category category, Vendor vendorInformation,Boolean pkGuide,Boolean pkJungle,Boolean pkShows,Boolean pkSports,Boolean pkCampfire,Boolean pkSeaActivity,
			String pkCode, String pkName, String pkPlace, BigDecimal pkCost,Boolean pkPickUp,
			String pkIsFlexible, int pkDays, int pkNights, Boolean pkFlight,
			Boolean pkHotel, Boolean pkFood, Boolean pkTrain, Boolean pkBus,
			Boolean pkFerry, Boolean pkTransfer, Boolean pkIsactive,
			String pkDescripton, Date pkModifiedOn, String pkModifiedBy,boolean pkPrice,boolean pkActivity,boolean pkHotels,String imageUrl,String tileImageUrl,String pkSpecial,Integer pkOrder) {
		this.category = category;
		this.vendorInformation = vendorInformation;
		this.pkCode = pkCode;
		this.pkName = pkName;
		this.pkPlace = pkPlace;
		this.pkCost = pkCost;
		this.pkIsFlexible = pkIsFlexible;
		this.pkDays = pkDays;
		this.pkNights = pkNights;
		this.pkFlight = pkFlight;
		this.pkHotel = pkHotel;
		this.pkFood = pkFood;
		this.pkTrain = pkTrain;
		this.pkBus = pkBus;
		this.pkFerry = pkFerry;
		this.pkTransfer = pkTransfer;
		this.pkIsactive = pkIsactive;
		this.pkDescripton = pkDescripton;
		this.pkModifiedOn = pkModifiedOn;
		this.pkModifiedBy = pkModifiedBy;
		this.pkPrice = pkPrice;
		this.pkActivity = pkActivity;
		this.pkHotels = pkHotels;
		this.imageUrl = imageUrl;
		this.tileImageUrl = tileImageUrl;
		this.pkSpecial = pkSpecial;
		this.pkGuide = pkGuide;
		this.pkJungle = pkJungle;
		this.pkShows = pkShows;
		this.pkCampfire = pkCampfire;
		this.pkSports = pkSports;
		this.pkSeaActivity = pkSeaActivity;
		this.pkPickUp = pkPickUp;
	}

	public Package(Category category, Vendor vendorInformation,Boolean pkGuide,Boolean pkJungle,Boolean pkShows,Boolean pkSports,Boolean pkCampfire,Boolean pkSeaActivity,
			String pkCode, String pkName, String pkPlace, BigDecimal pkCost,Boolean pkPickUp,
			String pkIsFlexible, int pkType, Integer pkRating, int pkDays,
			int pkNights, Boolean pkFlight, Boolean pkHotel, Boolean pkFood,
			Boolean pkTrain, Boolean pkBus, Boolean pkFerry,
			Boolean pkVisaFeeInclusion, Boolean pkTransfer, Integer pkDistance,
			Date pkValidFrom, Date pkValidTo, Boolean pkIsactive,
			String pkFilePath, String pkDescripton, Date pkModifiedOn,
			String pkModifiedBy,boolean pkPrice,boolean pkActivity,boolean pkHotels,String imageUrl,String tileImageUrl,String pkSpecial,Integer pkOrder) {
		this.category = category;
		this.vendorInformation = vendorInformation;
		this.pkCode = pkCode;
		this.pkName = pkName;
		this.pkPlace = pkPlace;
		this.pkCost = pkCost;
		this.pkIsFlexible = pkIsFlexible;
		this.pkType = pkType;
		this.pkRating = pkRating;
		this.pkDays = pkDays;
		this.pkNights = pkNights;
		this.pkFlight = pkFlight;
		this.pkHotel = pkHotel;
		this.pkFood = pkFood;
		this.pkTrain = pkTrain;
		this.pkBus = pkBus;
		this.pkFerry = pkFerry;
		this.pkVisaFeeInclusion = pkVisaFeeInclusion;
		this.pkTransfer = pkTransfer;
		this.pkDistance = pkDistance;
		this.pkValidFrom = pkValidFrom;
		this.pkValidTo = pkValidTo;
		this.pkIsactive = pkIsactive;
		this.pkFilePath = pkFilePath;
		this.pkDescripton = pkDescripton;
		this.pkModifiedOn = pkModifiedOn;
		this.pkModifiedBy = pkModifiedBy;
		this.pkPrice = pkPrice;
		this.pkActivity = pkActivity;
		this.pkHotels = pkHotels;
		this.imageUrl = imageUrl;
		this.tileImageUrl = tileImageUrl;
		this.pkSpecial = pkSpecial;
		this.pkGuide = pkGuide;
		this.pkJungle = pkJungle;
		this.pkShows = pkShows;
		this.pkCampfire = pkCampfire;
		this.pkSports = pkSports;
		this.pkSeaActivity = pkSeaActivity;
		this.pkPickUp = pkPickUp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pk_id", unique = true, nullable = false)
	public Integer getPkId() {
		return this.pkId;
	}

	public void setPkId(Integer pkId) {
		this.pkId = pkId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pk_cat_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pk_vi_seq_id", nullable = false)
	public Vendor getVendorInformation() {
		return this.vendorInformation;
	}

	public void setVendorInformation(Vendor vendorInformation) {
		this.vendorInformation = vendorInformation;
	}

	@Column(name = "pk_code", nullable = false, length = 50)
	public String getPkCode() {
		return this.pkCode;
	}

	public void setPkCode(String pkCode) {
		this.pkCode = pkCode;
	}

	@Column(name = "pk_name", nullable = false, length = 50)
	public String getPkName() {
		return this.pkName;
	}

	public void setPkName(String pkName) {
		this.pkName = pkName;
	}

	@Column(name = "pk_place", length = 50)
	public String getPkPlace() {
		return this.pkPlace;
	}

	public void setPkPlace(String pkPlace) {
		this.pkPlace = pkPlace;
	}

	@Column(name = "pk_cost", nullable = false, precision = 10)
	public BigDecimal getPkCost() {
		return this.pkCost;
	}

	public void setPkCost(BigDecimal pkCost) {
		this.pkCost = pkCost;
	}

	@Column(name = "pk_is_flexible", nullable = false, length = 5)
	public String getPkIsFlexible() {
		return this.pkIsFlexible;
	}

	public void setPkIsFlexible(String pkIsFlexible) {
		this.pkIsFlexible = pkIsFlexible;
	}

	@Column(name = "pk_type")
	public Integer getPkType() {
		return this.pkType;
	}

	public void setPkType(Integer pkType) {
		this.pkType = pkType;
	}

	@Column(name = "pk_rating")
	public Integer getPkRating() {
		return this.pkRating;
	}

	public void setPkRating(Integer pkRating) {
		this.pkRating = pkRating;
	}

	@Column(name = "pk_days", nullable = false)
	public Integer getPkDays() {
		return this.pkDays;
	}

	public void setPkDays(Integer pkDays) {
		this.pkDays = pkDays;
	}

	@Column(name = "pk_nights", nullable = false)
	public Integer getPkNights() {
		return this.pkNights;
	}

	public void setPkNights(Integer pkNights) {
		this.pkNights = pkNights;
	}

	@Column(name = "pk_distance")
	public Integer getPkDistance() {
		return this.pkDistance;
	}

	public void setPkDistance(Integer pkDistance) {
		this.pkDistance = pkDistance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pk_valid_from", length = 0)
	public Date getPkValidFrom() {
		return this.pkValidFrom;
	}

	public void setPkValidFrom(Date pkValidFrom) {
		this.pkValidFrom = pkValidFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pk_valid_to", length = 0)
	public Date getPkValidTo() {
		return this.pkValidTo;
	}

	public void setPkValidTo(Date pkValidTo) {
		this.pkValidTo = pkValidTo;
	}

	@Column(name = "pk_is_active", nullable = false, length = 6)
	public Boolean getPkIsactive() {
		return this.pkIsactive;
	}

	public void setPkIsactive(Boolean pkIsactive) {
		this.pkIsactive = pkIsactive;
	}

	@Column(name = "pk_file_path", length = 300)
	public String getPkFilePath() {
		return this.pkFilePath;
	}

	public void setPkFilePath(String pkFilePath) {
		this.pkFilePath = pkFilePath;
	}

	@Column(name = "pk_descripton", nullable = false, length = 500)
	public String getPkDescripton() {
		return this.pkDescripton;
	}

	public void setPkDescripton(String pkDescripton) {
		this.pkDescripton = pkDescripton;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pk_modified_on", nullable = false, length = 0)
	public Date getPkModifiedOn() {
		return this.pkModifiedOn;
	}

	public void setPkModifiedOn(Date pkModifiedOn) {
		this.pkModifiedOn = pkModifiedOn;
	}

	@Column(name = "pk_modified_by", nullable = false, length = 30)
	public String getPkModifiedBy() {
		return this.pkModifiedBy;
	}

	public void setPkModifiedBy(String pkModifiedBy) {
		this.pkModifiedBy = pkModifiedBy;
	}
	
	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Override
	public String toString() {
		return "Package [pkId=" + pkId + ", category=" + category
				+ ", vendorInformation=" + vendorInformation + ", pkCode="
				+ pkCode + ", pkName=" + pkName + ", pkPlace=" + pkPlace
				+ ", pkCost=" + pkCost + ", pkIsFlexible=" + pkIsFlexible
				+ ", pkType=" + pkType + ", pkRating=" + pkRating + ", pkDays="
				+ pkDays + ", pkNights=" + pkNights + ", pkFlight=" + pkFlight
				+ ", pkHotel=" + pkHotel + ", pkFood=" + pkFood + ", pkTrain="
				+ pkTrain + ", pkBus=" + pkBus + ", pkFerry=" + pkFerry
				+ ", pkVisaFeeInclusion=" + pkVisaFeeInclusion
				+ ", pkTransfer=" + pkTransfer + ", pkDistance=" + pkDistance
				+ ", pkValidFrom=" + pkValidFrom + ", pkValidTo=" + pkValidTo
				+ ", pkIsactive=" + pkIsactive + ", pkFilePath=" + pkFilePath
				+ ", pkDescripton=" + pkDescripton + ", pkModifiedOn="
				+ pkModifiedOn + ", pkModifiedBy=" + pkModifiedBy+ "]";
	}
	
	@Column(name = "pk_price")
	public boolean isPkPrice() {
		return pkPrice;
	}

	public void setPkPrice(boolean pkPrice) {
		this.pkPrice = pkPrice;
	}
	
	@Column(name = "pk_activity")
	public boolean isPkActivity() {
		return pkActivity;
	}

	public void setPkActivity(boolean pkActivity) {
		this.pkActivity = pkActivity;
	}
	
	@Column(name = "pk_hotels")
	public boolean isPkHotels() {
		return pkHotels;
	}

	public void setPkHotels(boolean pkHotels) {
		this.pkHotels = pkHotels;
	}
	
	@Column(name = "image_url")
	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		if(imageUrl != null){
			this.imageUrl = imageUrl.replace("\\", "/");
		}else{this.imageUrl = imageUrl;}
	}
	
	@Column(name = "pk_special")
	public String getPkSpecial() {
		return pkSpecial;
	}

	public void setPkSpecial(String pkSpecial) {
		this.pkSpecial = pkSpecial;
	}
	
	@Column(name = "pk_order")
	public Integer getPkOrder() {
		return pkOrder;
	}

	public void setPkOrder(Integer pkOrder) {
		this.pkOrder = pkOrder;
	}
	
	@Transient
	public String getActiveModel() {
		if(pkIsactive != null && pkIsactive){
			this.activeModel = "Y";
		} else {
			this.activeModel = "N";
		}
		return activeModel;
	}

	public void setActiveModel(String activeModel) {
			this.activeModel = activeModel;
	}
	
	@Column(name = "pk_flight", nullable = false, length = 6)
	public Boolean getPkFlight() {
		return pkFlight;
	}

	public void setPkFlight(Boolean pkFlight) {
		this.pkFlight = pkFlight;
	}
	
	@Column(name = "pk_hotel", nullable = false, length = 6)
	public Boolean getPkHotel() {
		return pkHotel;
	}

	public void setPkHotel(Boolean pkHotel) {
		this.pkHotel = pkHotel;
	}
	
	@Column(name = "pk_food", nullable = false, length = 6)
	public Boolean getPkFood() {
		return pkFood;
	}

	public void setPkFood(Boolean pkFood) {
		this.pkFood = pkFood;
	}
	
	@Column(name = "pk_train", nullable = false, length = 6)
	public Boolean getPkTrain() {
		return pkTrain;
	}

	public void setPkTrain(Boolean pkTrain) {
		this.pkTrain = pkTrain;
	}
	
	@Column(name = "pk_bus", nullable = false, length = 6)
	public Boolean getPkBus() {
		return pkBus;
	}

	public void setPkBus(Boolean pkBus) {
		this.pkBus = pkBus;
	}
	
	@Column(name = "pk_ferry", nullable = false, length = 6)
	public Boolean getPkFerry() {
		return pkFerry;
	}

	public void setPkFerry(Boolean pkFerry) {
		this.pkFerry = pkFerry;
	}
	
	@Column(name = "pk_visa_fee_inclusion", length = 6)
	public Boolean getPkVisaFeeInclusion() {
		return pkVisaFeeInclusion;
	}

	public void setPkVisaFeeInclusion(Boolean pkVisaFeeInclusion) {
		this.pkVisaFeeInclusion = pkVisaFeeInclusion;
	}
	
	@Column(name = "pk_transfer", nullable = false, length = 6)
	public Boolean getPkTransfer() {
		return pkTransfer;
	}

	public void setPkTransfer(Boolean pkTransfer) {
		this.pkTransfer = pkTransfer;
	}
	
	@Transient
	public String getPkFlightModel() {
		if(pkFlight != null && pkFlight){
			this.pkFlightModel = "Y";
		} else {
			this.pkFlightModel = "N";
		}
		return pkFlightModel;
	}

	public void setPkFlightModel(String pkFlightModel) {
		this.pkFlightModel = pkFlightModel;
	}
	
	@Transient
	public String getPkHotelModel() {
		if(pkHotel != null && pkHotel){
			this.pkHotelModel = "Y";
		} else {
			this.pkHotelModel = "N";
		}
		return pkHotelModel;
	}

	public void setPkHotelModel(String pkHotelModel) {
		this.pkHotelModel = pkHotelModel;
	}
	
	@Transient
	public String getPkFoodModel() {
		if(pkFood != null && pkFood){
			this.pkFoodModel = "Y";
		} else {
			this.pkFoodModel = "N";
		}
		return pkFoodModel;
	}

	public void setPkFoodModel(String pkFoodModel) {
		this.pkFoodModel = pkFoodModel;
	}
	
	@Transient
	public String getPkTrainModel() {
		if(pkTrain != null && pkTrain){
			this.pkTrainModel = "Y";
		} else {
			this.pkTrainModel = "N";
		}
		return pkTrainModel;
	}

	public void setPkTrainModel(String pkTrainModel) {
		this.pkTrainModel = pkTrainModel;
	}
	
	@Transient
	public String getPkBusModel() {
		if(pkBus != null && pkBus){
			this.pkBusModel = "Y";
		} else {
			this.pkBusModel = "N";
		}
		return pkBusModel;
	}

	public void setPkBusModel(String pkBusModel) {
		this.pkBusModel = pkBusModel;
	}
	
	@Transient
	public String getPkFerryModel() {
		if(pkFerry != null && pkFerry){
			this.pkFerryModel = "Y";
		} else {
			this.pkFerryModel = "N";
		}
		return pkFerryModel;
	}

	public void setPkFerryModel(String pkFerryModel) {
		this.pkFerryModel = pkFerryModel;
	}
	
	@Transient
	public String getPkVisaFeeInclusionModel() {
		if(pkVisaFeeInclusion != null && pkVisaFeeInclusion){
			this.pkVisaFeeInclusionModel = "Y";
		} else {
			this.pkVisaFeeInclusionModel = "N";
		}
		return pkVisaFeeInclusionModel;
	}

	public void setPkVisaFeeInclusionModel(String pkVisaFeeInclusionModel) {
		this.pkVisaFeeInclusionModel = pkVisaFeeInclusionModel;
	}
	
	@Transient
	public String getPkTransferModel() {
		if(pkTransfer != null && pkTransfer){
			this.pkTransferModel = "Y";
		} else {
			this.pkTransferModel = "N";
		}
		return pkTransferModel;
	}

	public void setPkTransferModel(String pkTransferModel) {
		this.pkTransferModel = pkTransferModel;
	}
	
	@Column(name = "is_valid", nullable = false, length = 6)
	public Boolean getIsValid() {
		return isValid;
	}

	public void setIsValid(Boolean isValid) {
		this.isValid = isValid;
	}
	
	@Column(name = "pk_guide", nullable = false, length = 6)
	public Boolean getPkGuide() {
		return pkGuide;
	}

	public void setPkGuide(Boolean pkGuide) {
		this.pkGuide = pkGuide;
	}
	
	@Column(name = "pk_jungle", nullable = false, length = 6)
	public Boolean getPkJungle() {
		return pkJungle;
	}

	public void setPkJungle(Boolean pkJungle) {
		this.pkJungle = pkJungle;
	}
	
	@Column(name = "pk_shows", nullable = false, length = 6)
	public Boolean getPkShows() {
		return pkShows;
	}

	public void setPkShows(Boolean pkShows) {
		this.pkShows = pkShows;
	}
	
	@Column(name = "pk_sports", nullable = false, length = 6)
	public Boolean getPkSports() {
		return pkSports;
	}

	public void setPkSports(Boolean pkSports) {
		this.pkSports = pkSports;
	}
	
	@Column(name = "pk_camp_fire", nullable = false, length = 6)
	public Boolean getPkCampfire() {
		return pkCampfire;
	}

	public void setPkCampfire(Boolean pkCampfire) {
		this.pkCampfire = pkCampfire;
	}
	
	@Column(name = "pk_sea_activity", nullable = false, length = 6)
	public Boolean getPkSeaActivity() {
		return pkSeaActivity;
	}

	public void setPkSeaActivity(Boolean pkSeaActivity) {
		this.pkSeaActivity = pkSeaActivity;
	}
	
	@Column(name = "pk_pickup", nullable = false, length = 6)
	public Boolean getPkPickUp() {
		return pkPickUp;
	}

	public void setPkPickUp(Boolean pkPickUp) {
		this.pkPickUp = pkPickUp;
	}
	
	@Column(name = "tile_image_url")
	public String getTileImageUrl() {
		return tileImageUrl;
	}
	
	public void setTileImageUrl(String tileImageUrl) {
		this.tileImageUrl = tileImageUrl;
	}
	
}
