package com.rave.visiit.entity;
// default package
// Generated 19 Feb, 2015 11:48:04 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.rave.visiit.util.Constants;

/**
 * PaymentTransaction generated by hbm2java
 */
@Entity
@Table(name = "payment_transaction", catalog = Constants.DB_CATELOG)
public class PaymentTransaction implements java.io.Serializable {

	private Integer ptid;
	private String mihpayid;
	private String status;
	private String key;
	private String txnid;
	private String name;
	private String product;
	private BigDecimal amount;
	private BigDecimal discount;
	private String offer;
	private String mode;
	private String bankcode;
	private String bankrefnum;
	private String pgtype;
	private String error;
	private String errormsg;
	private String hash;
	private Date updatedon;

	public PaymentTransaction() {
	}

	public PaymentTransaction(BigDecimal discount, Date updatedon) {
		this.discount = discount;
		this.updatedon = updatedon;
	}

	public PaymentTransaction(String mihpayid, String status, String key,
			String txnid, String name, String product, BigDecimal amount, BigDecimal discount,
			String offer, String mode, String bankcode, String bankrefnum,
			String pgtype, String error, String errormsg, String hash,
			Date updatedon) {
		this.mihpayid = mihpayid;
		this.status = status;
		this.key = key;
		this.txnid = txnid;
		this.name = name;
		this.amount = amount;
		this.product = product;
		this.discount = discount;
		this.offer = offer;
		this.mode = mode;
		this.bankcode = bankcode;
		this.bankrefnum = bankrefnum;
		this.pgtype = pgtype;
		this.error = error;
		this.errormsg = errormsg;
		this.hash = hash;
		this.updatedon = updatedon;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ptid", unique = true, nullable = false)
	public Integer getPtid() {
		return this.ptid;
	}

	public void setPtid(Integer ptid) {
		this.ptid = ptid;
	}

	@Column(name = "mihpayid", length = 55)
	public String getMihpayid() {
		return this.mihpayid;
	}

	public void setMihpayid(String mihpayid) {
		this.mihpayid = mihpayid;
	}

	@Column(name = "status", length = 25)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "merchantkey", length = 10)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "txnid", length = 10)
	public String getTxnid() {
		return this.txnid;
	}

	public void setTxnid(String txnid) {
		this.txnid = txnid;
	}

	@Column(name = "name", length = 55)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "product", length = 100)
	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	@Column(name = "amount", nullable = false, precision = 10)
	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "discount", nullable = false, precision = 10)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "offer", length = 10)
	public String getOffer() {
		return this.offer;
	}

	public void setOffer(String offer) {
		this.offer = offer;
	}

	@Column(name = "mode", length = 10)
	public String getMode() {
		return this.mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	@Column(name = "bankcode", length = 25)
	public String getBankcode() {
		return this.bankcode;
	}

	public void setBankcode(String bankcode) {
		this.bankcode = bankcode;
	}

	@Column(name = "bankrefnum", length = 30)
	public String getBankrefnum() {
		return this.bankrefnum;
	}

	public void setBankrefnum(String bankrefnum) {
		this.bankrefnum = bankrefnum;
	}

	@Column(name = "pgtype", length = 30)
	public String getPgtype() {
		return this.pgtype;
	}

	public void setPgtype(String pgtype) {
		this.pgtype = pgtype;
	}

	@Column(name = "error", length = 30)
	public String getError() {
		return this.error;
	}

	public void setError(String error) {
		this.error = error;
	}

	@Column(name = "errormsg", length = 500)
	public String getErrormsg() {
		return this.errormsg;
	}

	public void setErrormsg(String errormsg) {
		this.errormsg = errormsg;
	}

	@Column(name = "hash", length = 500)
	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedon", nullable = false, length = 0)
	public Date getUpdatedon() {
		return this.updatedon;
	}

	public void setUpdatedon(Date updatedon) {
		this.updatedon = updatedon;
	}

	@Override
	public String toString() {
		return "PaymentTransaction [ptid=" + ptid + ", mihpayid=" + mihpayid
				+ ", status=" + status + ", key=" + key + ", txnid=" + txnid
				+ ", name=" + name + ", product=" + product + ", amount="
				+ amount + ", discount=" + discount + ", offer=" + offer
				+ ", mode=" + mode + ", bankcode=" + bankcode + ", bankrefnum="
				+ bankrefnum + ", pgtype=" + pgtype + ", error=" + error
				+ ", errormsg=" + errormsg + ", hash=" + hash + ", updatedon="
				+ updatedon + "]";
	}

}
