package com.rave.visiit.entity;
// default package
// Generated 24 Dec, 2014 7:54:49 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.rave.visiit.util.Constants;

/**
 * RoleMaster generated by hbm2java
 */
@Entity
@Table(name = "role_master", catalog = Constants.DB_CATELOG)
public class RoleMaster implements java.io.Serializable {

	private Integer roleId;
	private String roleTitle;
	private String roleDiscription;
	private Date updatedDate;
	
	@Transient
	private Set<User> userses = new HashSet<User>(0);

	public RoleMaster() {
	}

	public RoleMaster(String roleTitle, String roleDiscription, Date updatedDate) {
		this.roleTitle = roleTitle;
		this.roleDiscription = roleDiscription;
		this.updatedDate = updatedDate;
	}

	public RoleMaster(String roleTitle, String roleDiscription,
			Date updatedDate, Set<User> userses) {
		this.roleTitle = roleTitle;
		this.roleDiscription = roleDiscription;
		this.updatedDate = updatedDate;
		this.userses = userses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "role_id", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_title", nullable = false, length = 30)
	public String getRoleTitle() {
		return this.roleTitle;
	}

	public void setRoleTitle(String roleTitle) {
		this.roleTitle = roleTitle;
	}

	@Column(name = "role_discription", nullable = false, length = 50)
	public String getRoleDiscription() {
		return this.roleDiscription;
	}

	public void setRoleDiscription(String roleDiscription) {
		this.roleDiscription = roleDiscription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 0)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "roleMaster")
	@Transient
	public Set<User> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<User> userses) {
		this.userses = userses;
	}

}
