package com.rave.visiit.entity;
// default package
// Generated 24 Dec, 2014 7:54:49 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.rave.visiit.util.Constants;

/**
 * SecurityQuestion generated by hbm2java
 */
@Entity
@Table(name = "security_question", catalog = Constants.DB_CATELOG)
public class SecurityQuestion implements java.io.Serializable {

	private Integer sqId;
	private String sqQuestion;
	private String sqType;
	private Date sqUpdatedDate;

	@Transient
	private Set<User> userses = new HashSet<User>(0);

	public SecurityQuestion() {
	}

	public SecurityQuestion(String sqQuestion, String sqType, Date sqUpdatedDate) {
		this.sqQuestion = sqQuestion;
		this.sqType = sqType;
		this.sqUpdatedDate = sqUpdatedDate;
	}

	public SecurityQuestion(String sqQuestion, String sqType,
			Date sqUpdatedDate, Set<User> userses) {
		this.sqQuestion = sqQuestion;
		this.sqType = sqType;
		this.sqUpdatedDate = sqUpdatedDate;
		this.userses = userses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sq_id", unique = true, nullable = false)
	public Integer getSqId() {
		return this.sqId;
	}

	public void setSqId(Integer sqId) {
		this.sqId = sqId;
	}

	@Column(name = "sq_question", nullable = false, length = 40)
	public String getSqQuestion() {
		return this.sqQuestion;
	}

	public void setSqQuestion(String sqQuestion) {
		this.sqQuestion = sqQuestion;
	}

	@Column(name = "sq_type", nullable = false, length = 20)
	public String getSqType() {
		return this.sqType;
	}

	public void setSqType(String sqType) {
		this.sqType = sqType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sq_updated_date", nullable = false, length = 0)
	public Date getSqUpdatedDate() {
		return this.sqUpdatedDate;
	}

	public void setSqUpdatedDate(Date sqUpdatedDate) {
		this.sqUpdatedDate = sqUpdatedDate;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "securityQuestion")
	@Transient
	public Set<User> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<User> userses) {
		this.userses = userses;
	}

}
