package com.rave.visiit.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Timestamp;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

import com.rave.visiit.util.Constants;

/**
 * User generated by hbm2java
 */

@Entity
@Table(name = "user", catalog = Constants.DB_CATELOG)
public class User implements java.io.Serializable {

	private static final long serialVersionUID = 5700928979934983029L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_seq_id", unique = true, nullable = false)
	private Integer userSeqId;

	@Column(name = "user_id", nullable = false, length = 50)
	private String userId;

	@Column(name = "user_code", nullable = false, length = 30)
	private String userCode;

	@Column(name = "user_password", length = 50)
	private String userPassword;

	@Column(name = "user_is_active")
	private Boolean userIsActive = Boolean.TRUE;;

	@Column(name = "is_deleted")
	private Boolean isDeleted = Boolean.FALSE;;

	@Column(name = "user_first_name", nullable = false, length = 30)
	private String userFirstName;

	@Column(name = "user_last_name", nullable = false, length = 30)
	private String userLastName;

	@Column(name = "user_office_mail", length = 50)
	private String userOfficeMail;

	@Column(name = "user_mail", length = 50)
	private String userMail;

	@Column(name = "user_phone", nullable = false, length = 15)
	private String userPhone;

	@Column(name = "user_extention_no", length = 10)
	private String userExtentionNo;

	@Column(name = "user_dept_id", nullable = false, length = 11)
	private String userDeptId;

	@Column(name = "user_dsg_id", nullable = false, length = 11)
	private String userDsgId;

	@Column(name = "user_doj")
	private Date userDoj;

	@Column(name = "user_esi_no", length = 20)
	private String userEsiNo;

	@Column(name = "user_pf_no", length = 20)
	private String userPfNo;

	@Column(name = "user_pan_no", length = 20)
	private String userPanNo;

	@Column(name = "user_passport_no", length = 20)
	private String userPassportNo;

	@Column(name = "user_dob")
	private Date userDob;

	@Column(name = "user_created_by", nullable = false, length = 30)
	private String userCreatedBy;

	@Column(name = "user_created_on", nullable = false)
	private Timestamp userCreatedOn;

	@Column(name = "user_modified_by", nullable = false, length = 30)
	private String userModifiedBy;

	@Column(name = "user_modified_on", nullable = false)
	private Timestamp userModifiedOn;

	@Column(name = "user_pwd_exp_date", nullable = false)
	private Timestamp userPwdExpDate;
	
	@ManyToMany(cascade = CascadeType.ALL)
	@JoinTable(name = "user_module", joinColumns = {
	@JoinColumn(name = "user_seq_id", nullable = false, updatable = false) },
	   inverseJoinColumns = { @JoinColumn(name = "mod_id",
	   nullable = false, updatable = false) })
	@LazyCollection(LazyCollectionOption.FALSE)
	private List<Module> userModules;
	
	@ManyToMany(cascade = CascadeType.ALL)
	@JoinTable(name = "user_sub_module", joinColumns = {
	@JoinColumn(name = "user_seq_id", nullable = false, updatable = false) },
	   inverseJoinColumns = { @JoinColumn(name = "mod_id",
	nullable = false, updatable = false) })
	@LazyCollection(LazyCollectionOption.FALSE)
	private List<Module> userSubModules;
	

	public User() {
	}


	public Integer getUserSeqId() {
		return userSeqId;
	}
	public void setUserSeqId(Integer userSeqId) {
		this.userSeqId = userSeqId;
	}

	public String getUserId() {
		return userId;
	}
	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserCode() {
		return userCode;
	}
	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getUserPassword() {
		return userPassword;
	}
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public Boolean getUserIsActive() {
		return userIsActive;
	}
	public void setUserIsActive(Boolean userIsActive) {
		this.userIsActive = userIsActive;
	}

	public Boolean getIsDeleted() {
		return isDeleted;
	}
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public String getUserFirstName() {
		return userFirstName;
	}
	public void setUserFirstName(String userFirstName) {
		this.userFirstName = userFirstName;
	}

	public String getUserLastName() {
		return userLastName;
	}
	public void setUserLastName(String userLastName) {
		this.userLastName = userLastName;
	}

	public String getUserOfficeMail() {
		return userOfficeMail;
	}
	public void setUserOfficeMail(String userOfficeMail) {
		this.userOfficeMail = userOfficeMail;
	}

	public String getUserMail() {
		return userMail;
	}
	public void setUserMail(String userMail) {
		this.userMail = userMail;
	}

	public String getUserPhone() {
		return userPhone;
	}
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	public String getUserExtentionNo() {
		return userExtentionNo;
	}
	public void setUserExtentionNo(String userExtentionNo) {
		this.userExtentionNo = userExtentionNo;
	}

	public String getUserDeptId() {
		return userDeptId;
	}
	public void setUserDeptId(String userDeptId) {
		this.userDeptId = userDeptId;
	}

	public String getUserDsgId() {
		return userDsgId;
	}
	public void setUserDsgId(String userDsgId) {
		this.userDsgId = userDsgId;
	}

	public Date getUserDoj() {
		return userDoj;
	}
	public void setUserDoj(Date userDoj) {
		this.userDoj = userDoj;
	}

	public String getUserEsiNo() {
		return userEsiNo;
	}
	public void setUserEsiNo(String userEsiNo) {
		this.userEsiNo = userEsiNo;
	}

	public String getUserPfNo() {
		return userPfNo;
	}
	public void setUserPfNo(String userPfNo) {
		this.userPfNo = userPfNo;
	}

	public String getUserPanNo() {
		return userPanNo;
	}
	public void setUserPanNo(String userPanNo) {
		this.userPanNo = userPanNo;
	}

	public String getUserPassportNo() {
		return userPassportNo;
	}
	public void setUserPassportNo(String userPassportNo) {
		this.userPassportNo = userPassportNo;
	}

	public Date getUserDob() {
		return userDob;
	}
	public void setUserDob(Date userDob) {
		this.userDob = userDob;
	}

	public String getUserCreatedBy() {
		return userCreatedBy;
	}
	public void setUserCreatedBy(String userCreatedBy) {
		this.userCreatedBy = userCreatedBy;
	}

	public Timestamp getUserCreatedOn() {
		return userCreatedOn;
	}
	public void setUserCreatedOn(Timestamp userCreatedOn) {
		this.userCreatedOn = userCreatedOn;
	}

	public String getUserModifiedBy() {
		return userModifiedBy;
	}
	public void setUserModifiedBy(String userModifiedBy) {
		this.userModifiedBy = userModifiedBy;
	}

	public Timestamp getUserModifiedOn() {
		return userModifiedOn;
	}
	public void setUserModifiedOn(Timestamp userModifiedOn) {
		this.userModifiedOn = userModifiedOn;
	}

	@Transient
	private RoleMaster roleMaster;

	@Transient
	private SecurityQuestion securityQuestion;
	/*private Set<AppLogin> appLogins = new HashSet<AppLogin>(0);*/

	//@ManyToOne(fetch = FetchType.LAZY)
	//@JoinColumn(name = "role_id", nullable = false)
	public RoleMaster getRoleMaster() {
		return this.roleMaster;
	}

	public void setRoleMaster(RoleMaster roleMaster) {
		this.roleMaster = roleMaster;
	}
	
	//@ManyToOne(fetch = FetchType.LAZY)
	//@JoinColumn(name = "user_sq_id", nullable = false)
	public SecurityQuestion getSecurityQuestion() {
		return this.securityQuestion;
	}

	public void setSecurityQuestion(SecurityQuestion securityQuestion) {
		this.securityQuestion = securityQuestion;
	}


	public Timestamp getUserPwdExpDate() {
		return userPwdExpDate;
	}

	public void setUserPwdExpDate(Timestamp userPwdExpDate) {
		this.userPwdExpDate = userPwdExpDate;
	}


	public List<Module> getUserModules() {
		return userModules;
	}


	public void setUserModules(List<Module> userModules) {
		this.userModules = userModules;
	}


	public List<Module> getUserSubModules() {
		return userSubModules;
	}


	public void setUserSubModules(List<Module> userSubModules) {
		this.userSubModules = userSubModules;
	}
	
	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<AppLogin> getAppLogins() {
		return this.appLogins;
	}

	public void setAppLogins(Set<AppLogin> appLogins) {
		this.appLogins = appLogins;
	}*/
}

