package com.rave.visiit.entity;
// default package
// Generated 29 Dec, 2014 3:09:30 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.rave.visiit.util.Constants;

/**
 * VendorInformation generated by hbm2java
 */
@Entity
@Table(name = "vendor_information", catalog = Constants.DB_CATELOG)
public class Vendor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer viSeqId;
	private int viVendorId;
	private String viVendorName;
	private String viVendorEmail;
	private String viVendorPhone;
	private String viContactName1;
	private String viContactNo1;
	private String viContactEmail1;
	private String viContactPosition1;
	private String viContactName2;
	private String viContactNo2;
	private String viContactEmail2;
	private String viContactPosition2;
	private String viRemark;
	private Integer viRating;
	private Boolean viIsactive = Boolean.TRUE;
	private String viAddress;
	private String viCity;
	private String viState;
	private String viCountry;
	private String viPincode;
	private String viFax;
	private String viRelationship;
	private Date viModifiedOn;
	private String viModifiedBy;
	private String viCode;
	private Boolean isDeleted = Boolean.FALSE;
	@Transient
	private String activeModel;
	//private Set<Package> packages = new HashSet<Package>(0);

	public Vendor() {
	}

	public Vendor(int viVendorId, String viVendorName,
			String viVendorEmail, String viVendorPhone, String viContactName1,
			String viContactNo1, String viContactEmail1, Boolean viIsactive,
			Date viModifiedOn, String viModifiedBy,String viCode,Set<Package> packages,Boolean isDeleted) {
		this.viVendorId = viVendorId;
		this.viVendorName = viVendorName;
		this.viVendorEmail = viVendorEmail;
		this.viVendorPhone = viVendorPhone;
		this.viContactName1 = viContactName1;
		this.viContactNo1 = viContactNo1;
		this.viContactEmail1 = viContactEmail1;
		this.viIsactive = viIsactive;
		this.viModifiedOn = viModifiedOn;
		this.viModifiedBy = viModifiedBy;
		this.viCode = viCode;
		this.isDeleted = isDeleted;
		//this.packages = packages;
	}

	public Vendor(int viVendorId, String viVendorName,
			String viVendorEmail, String viVendorPhone, String viContactName1,
			String viContactNo1, String viContactEmail1,
			String viContactPosition1, String viContactName2,
			String viContactNo2, String viContactEmail2,
			String viContactPosition2, String viRemark, Integer viRating,
			Boolean viIsactive, String viAddress, String viCity, String viState,
			String viCountry, String viPincode, String viFax,
			String viRelationship, Date viModifiedOn, String viModifiedBy,String viCode, Set<Package> packages,Boolean isDeleted
			) {
		this.viVendorId = viVendorId;
		this.viVendorName = viVendorName;
		this.viVendorEmail = viVendorEmail;
		this.viVendorPhone = viVendorPhone;
		this.viContactName1 = viContactName1;
		this.viContactNo1 = viContactNo1;
		this.viContactEmail1 = viContactEmail1;
		this.viContactPosition1 = viContactPosition1;
		this.viContactName2 = viContactName2;
		this.viContactNo2 = viContactNo2;
		this.viContactEmail2 = viContactEmail2;
		this.viContactPosition2 = viContactPosition2;
		this.viRemark = viRemark;
		this.viRating = viRating;
		this.viIsactive = viIsactive;
		this.viAddress = viAddress;
		this.viCity = viCity;
		this.viState = viState;
		this.viCountry = viCountry;
		this.viPincode = viPincode;
		this.viFax = viFax;
		this.viRelationship = viRelationship;
		this.viModifiedOn = viModifiedOn;
		this.viModifiedBy = viModifiedBy;
		this.viCode = viCode;
		this.isDeleted = isDeleted;
		//this.packages = packages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "vi_seq_id", unique = true, nullable = false)
	public Integer getViSeqId() {
		return this.viSeqId;
	}

	public void setViSeqId(Integer viSeqId) {
		this.viSeqId = viSeqId;
	}

	@Column(name = "vi_vendor_id", nullable = false)
	public int getViVendorId() {
		return this.viVendorId;
	}

	public void setViVendorId(int viVendorId) {
		this.viVendorId = viVendorId;
	}

	@Column(name = "vi_vendor_name", nullable = false, length = 50)
	public String getViVendorName() {
		return this.viVendorName;
	}

	public void setViVendorName(String viVendorName) {
		this.viVendorName = viVendorName;
	}

	@Column(name = "vi_vendor_email", nullable = false, length = 50)
	public String getViVendorEmail() {
		return this.viVendorEmail;
	}

	public void setViVendorEmail(String viVendorEmail) {
		this.viVendorEmail = viVendorEmail;
	}

	@Column(name = "vi_vendor_phone", nullable = false, length = 15)
	public String getViVendorPhone() {
		return this.viVendorPhone;
	}

	public void setViVendorPhone(String viVendorPhone) {
		this.viVendorPhone = viVendorPhone;
	}

	@Column(name = "vi_contact_name1", nullable = false, length = 50)
	public String getViContactName1() {
		return this.viContactName1;
	}

	public void setViContactName1(String viContactName1) {
		this.viContactName1 = viContactName1;
	}

	@Column(name = "vi_contact_no1", nullable = false, length = 15)
	public String getViContactNo1() {
		return this.viContactNo1;
	}

	public void setViContactNo1(String viContactNo1) {
		this.viContactNo1 = viContactNo1;
	}

	@Column(name = "vi_contact_email1", nullable = false, length = 50)
	public String getViContactEmail1() {
		return this.viContactEmail1;
	}

	public void setViContactEmail1(String viContactEmail1) {
		this.viContactEmail1 = viContactEmail1;
	}

	@Column(name = "vi_contact_position1", length = 30)
	public String getViContactPosition1() {
		return this.viContactPosition1;
	}

	public void setViContactPosition1(String viContactPosition1) {
		this.viContactPosition1 = viContactPosition1;
	}

	@Column(name = "vi_contact_name2", length = 50)
	public String getViContactName2() {
		return this.viContactName2;
	}

	public void setViContactName2(String viContactName2) {
		this.viContactName2 = viContactName2;
	}

	@Column(name = "vi_contact_no2", length = 15)
	public String getViContactNo2() {
		return this.viContactNo2;
	}

	public void setViContactNo2(String viContactNo2) {
		this.viContactNo2 = viContactNo2;
	}

	@Column(name = "vi_contact_email2", length = 50)
	public String getViContactEmail2() {
		return this.viContactEmail2;
	}

	public void setViContactEmail2(String viContactEmail2) {
		this.viContactEmail2 = viContactEmail2;
	}

	@Column(name = "vi_contact_position2", length = 30)
	public String getViContactPosition2() {
		return this.viContactPosition2;
	}

	public void setViContactPosition2(String viContactPosition2) {
		this.viContactPosition2 = viContactPosition2;
	}

	@Column(name = "vi_remark", length = 100)
	public String getViRemark() {
		return this.viRemark;
	}

	public void setViRemark(String viRemark) {
		this.viRemark = viRemark;
	}

	@Column(name = "vi_rating")
	public Integer getViRating() {
		return this.viRating;
	}

	public void setViRating(Integer viRating) {
		this.viRating = viRating;
	}

	@Column(name = "vi_address", length = 100)
	public String getViAddress() {
		return this.viAddress;
	}

	public void setViAddress(String viAddress) {
		this.viAddress = viAddress;
	}

	@Column(name = "vi_city", length = 50)
	public String getViCity() {
		return this.viCity;
	}

	public void setViCity(String viCity) {
		this.viCity = viCity;
	}

	@Column(name = "vi_state", length = 50)
	public String getViState() {
		return this.viState;
	}

	public void setViState(String viState) {
		this.viState = viState;
	}

	@Column(name = "vi_country", length = 50)
	public String getViCountry() {
		return this.viCountry;
	}

	public void setViCountry(String viCountry) {
		this.viCountry = viCountry;
	}

	@Column(name = "vi_pincode", length = 15)
	public String getViPincode() {
		return this.viPincode;
	}

	public void setViPincode(String viPincode) {
		this.viPincode = viPincode;
	}

	@Column(name = "vi_fax", length = 15)
	public String getViFax() {
		return this.viFax;
	}

	public void setViFax(String viFax) {
		this.viFax = viFax;
	}

	@Column(name = "vi_relationship", length = 10)
	public String getViRelationship() {
		return this.viRelationship;
	}

	public void setViRelationship(String viRelationship) {
		this.viRelationship = viRelationship;
	}

	@Column(name = "vi_modified_by", nullable = false, length = 30)
	public String getViModifiedBy() {
		return this.viModifiedBy;
	}

	public void setViModifiedBy(String viModifiedBy) {
		this.viModifiedBy = viModifiedBy;
	}
	
	@Column(name = "vi_code",length = 50)
	public String getViCode() {
		return viCode;
	}
	
	public void setViCode(String viCode) {
		this.viCode = viCode;
	}

	/*@OneToMany(mappedBy = "vendorInformation")
	@Cascade({CascadeType.DELETE})
	public Set<Package> getPackages() {
		return this.packages;
	}

	public void setPackages(Set<Package> packages) {
		this.packages = packages;
	}*/
	
	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}
	
	@Column(name = "vi_is_active", nullable = false, length = 6)
	public Boolean getViIsactive() {
		return viIsactive;
	}

	public void setViIsactive(Boolean viIsactive) {
		this.viIsactive = viIsactive;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "vi_modified_on", nullable = false, length = 0)
	public Date getViModifiedOn() {
		return viModifiedOn;
	}

	public void setViModifiedOn(Date viModifiedOn) {
		this.viModifiedOn = viModifiedOn;
	}
	
	@Transient
	public String getActiveModel() {
		if(viIsactive != null && viIsactive){
			this.activeModel = "Y";
		} else {
			this.activeModel = "N";
		}
		return activeModel;
	}

	public void setActiveModel(String activeModel) {
			this.activeModel = activeModel;
	}
	
	
}
